// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package models

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes = "BasicAuth.Scopes"
	JWTAuthScopes   = "JWTAuth.Scopes"
	KeyAuthScopes   = "KeyAuth.Scopes"
)

// Defines values for FirewallRuleDirection.
const (
	FirewallRuleDirectionAny FirewallRuleDirection = "any"
	FirewallRuleDirectionIn  FirewallRuleDirection = "in"
	FirewallRuleDirectionOut FirewallRuleDirection = "out"
)

// Defines values for FirewallRuleIcmptype.
const (
	FirewallRuleIcmptypeAlthost   FirewallRuleIcmptype = "althost"
	FirewallRuleIcmptypeAny       FirewallRuleIcmptype = "any"
	FirewallRuleIcmptypeDataconv  FirewallRuleIcmptype = "dataconv"
	FirewallRuleIcmptypeEchorep   FirewallRuleIcmptype = "echorep"
	FirewallRuleIcmptypeEchoreq   FirewallRuleIcmptype = "echoreq"
	FirewallRuleIcmptypeInforep   FirewallRuleIcmptype = "inforep"
	FirewallRuleIcmptypeInforeq   FirewallRuleIcmptype = "inforeq"
	FirewallRuleIcmptypeIpv6Here  FirewallRuleIcmptype = "ipv6-here"
	FirewallRuleIcmptypeIpv6Where FirewallRuleIcmptype = "ipv6-where"
	FirewallRuleIcmptypeMaskrep   FirewallRuleIcmptype = "maskrep"
	FirewallRuleIcmptypeMaskreq   FirewallRuleIcmptype = "maskreq"
	FirewallRuleIcmptypeMobredir  FirewallRuleIcmptype = "mobredir"
	FirewallRuleIcmptypeMobregrep FirewallRuleIcmptype = "mobregrep"
	FirewallRuleIcmptypeMobregreq FirewallRuleIcmptype = "mobregreq"
	FirewallRuleIcmptypeParamprob FirewallRuleIcmptype = "paramprob"
	FirewallRuleIcmptypePhoturis  FirewallRuleIcmptype = "photuris"
	FirewallRuleIcmptypeRedir     FirewallRuleIcmptype = "redir"
	FirewallRuleIcmptypeRouteradv FirewallRuleIcmptype = "routeradv"
	FirewallRuleIcmptypeRoutersol FirewallRuleIcmptype = "routersol"
	FirewallRuleIcmptypeSkip      FirewallRuleIcmptype = "skip"
	FirewallRuleIcmptypeSquench   FirewallRuleIcmptype = "squench"
	FirewallRuleIcmptypeTimerep   FirewallRuleIcmptype = "timerep"
	FirewallRuleIcmptypeTimereq   FirewallRuleIcmptype = "timereq"
	FirewallRuleIcmptypeTimex     FirewallRuleIcmptype = "timex"
	FirewallRuleIcmptypeTrace     FirewallRuleIcmptype = "trace"
	FirewallRuleIcmptypeUnreach   FirewallRuleIcmptype = "unreach"
)

// Defines values for FirewallRuleIpprotocol.
const (
	Inet   FirewallRuleIpprotocol = "inet"
	Inet46 FirewallRuleIpprotocol = "inet46"
	Inet6  FirewallRuleIpprotocol = "inet6"
)

// Defines values for FirewallRuleProtocol.
const (
	Ah     FirewallRuleProtocol = "ah"
	Carp   FirewallRuleProtocol = "carp"
	Esp    FirewallRuleProtocol = "esp"
	Gre    FirewallRuleProtocol = "gre"
	Icmp   FirewallRuleProtocol = "icmp"
	Igmp   FirewallRuleProtocol = "igmp"
	Ipv6   FirewallRuleProtocol = "ipv6"
	Ospf   FirewallRuleProtocol = "ospf"
	Pfsync FirewallRuleProtocol = "pfsync"
	Pim    FirewallRuleProtocol = "pim"
	Tcp    FirewallRuleProtocol = "tcp"
	Tcpudp FirewallRuleProtocol = "tcp/udp"
	Udp    FirewallRuleProtocol = "udp"
)

// Defines values for FirewallRuleStatetype.
const (
	KeepState     FirewallRuleStatetype = "keep state"
	None          FirewallRuleStatetype = "none"
	SloppyState   FirewallRuleStatetype = "sloppy state"
	SynproxyState FirewallRuleStatetype = "synproxy state"
)

// Defines values for FirewallRuleTcpFlagsOutOf.
const (
	FirewallRuleTcpFlagsOutOfAck FirewallRuleTcpFlagsOutOf = "ack"
	FirewallRuleTcpFlagsOutOfCwr FirewallRuleTcpFlagsOutOf = "cwr"
	FirewallRuleTcpFlagsOutOfEce FirewallRuleTcpFlagsOutOf = "ece"
	FirewallRuleTcpFlagsOutOfFin FirewallRuleTcpFlagsOutOf = "fin"
	FirewallRuleTcpFlagsOutOfPsh FirewallRuleTcpFlagsOutOf = "psh"
	FirewallRuleTcpFlagsOutOfRst FirewallRuleTcpFlagsOutOf = "rst"
	FirewallRuleTcpFlagsOutOfSyn FirewallRuleTcpFlagsOutOf = "syn"
	FirewallRuleTcpFlagsOutOfUrg FirewallRuleTcpFlagsOutOf = "urg"
)

// Defines values for FirewallRuleTcpFlagsSet.
const (
	FirewallRuleTcpFlagsSetAck FirewallRuleTcpFlagsSet = "ack"
	FirewallRuleTcpFlagsSetCwr FirewallRuleTcpFlagsSet = "cwr"
	FirewallRuleTcpFlagsSetEce FirewallRuleTcpFlagsSet = "ece"
	FirewallRuleTcpFlagsSetFin FirewallRuleTcpFlagsSet = "fin"
	FirewallRuleTcpFlagsSetPsh FirewallRuleTcpFlagsSet = "psh"
	FirewallRuleTcpFlagsSetRst FirewallRuleTcpFlagsSet = "rst"
	FirewallRuleTcpFlagsSetSyn FirewallRuleTcpFlagsSet = "syn"
	FirewallRuleTcpFlagsSetUrg FirewallRuleTcpFlagsSet = "urg"
)

// Defines values for FirewallRuleType.
const (
	Block  FirewallRuleType = "block"
	Pass   FirewallRuleType = "pass"
	Reject FirewallRuleType = "reject"
)

// AuthenticationError defines model for AuthenticationError.
type AuthenticationError struct {
	// Links An array of links to resources that are related to this API response.
	Links *map[string]interface{} `json:"_links,omitempty"`

	// Code The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`

	// Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
	Data *AuthenticationError_Data `json:"data,omitempty"`

	// Message The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`

	// ResponseId The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseId *string `json:"response_id,omitempty"`

	// Status The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
}

// AuthenticationErrorData0 defines model for .
type AuthenticationErrorData0 = []map[string]interface{}

// AuthenticationErrorData1 defines model for .
type AuthenticationErrorData1 = map[string]interface{}

// AuthenticationError_Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
type AuthenticationError_Data struct {
	union json.RawMessage
}

// ConflictError defines model for ConflictError.
type ConflictError struct {
	// Links An array of links to resources that are related to this API response.
	Links *map[string]interface{} `json:"_links,omitempty"`

	// Code The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`

	// Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
	Data *ConflictError_Data `json:"data,omitempty"`

	// Message The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`

	// ResponseId The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseId *string `json:"response_id,omitempty"`

	// Status The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
}

// ConflictErrorData0 defines model for .
type ConflictErrorData0 = []map[string]interface{}

// ConflictErrorData1 defines model for .
type ConflictErrorData1 = map[string]interface{}

// ConflictError_Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
type ConflictError_Data struct {
	union json.RawMessage
}

// FailedDependencyError defines model for FailedDependencyError.
type FailedDependencyError struct {
	// Links An array of links to resources that are related to this API response.
	Links *map[string]interface{} `json:"_links,omitempty"`

	// Code The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`

	// Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
	Data *FailedDependencyError_Data `json:"data,omitempty"`

	// Message The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`

	// ResponseId The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseId *string `json:"response_id,omitempty"`

	// Status The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
}

// FailedDependencyErrorData0 defines model for .
type FailedDependencyErrorData0 = []map[string]interface{}

// FailedDependencyErrorData1 defines model for .
type FailedDependencyErrorData1 = map[string]interface{}

// FailedDependencyError_Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
type FailedDependencyError_Data struct {
	union json.RawMessage
}

// FirewallRule defines model for FirewallRule.
type FirewallRule struct {
	// Ackqueue The name of the traffic shaper queue to assume as the ACK queue for ACK traffic matching this rule.<br>
	Ackqueue *string `json:"ackqueue"`

	// AssociatedRuleId The internal rule ID for the NAT rule associated with this rule.<br>
	AssociatedRuleId *string `json:"associated_rule_id"`

	// CreatedBy The username and IP of the user who originally created this firewall rule.<br>
	CreatedBy *string `json:"created_by"`

	// CreatedTime The unix timestamp of when this firewall rule was original created.<br>
	CreatedTime *int `json:"created_time"`

	// Defaultqueue The name of the traffic shaper queue to assume as the default queue for traffic matching this rule.<br>
	Defaultqueue *string `json:"defaultqueue"`

	// Descr A description detailing the purpose or justification of this firewall rule.<br>
	Descr *string `json:"descr,omitempty"`

	// Destination The destination address this rule applies to. Valid value options are: an existing interface, an IP address, a subnet CIDR, an existing alias, `any`, `(self)`, `l2tp`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>
	Destination *string `json:"destination,omitempty"`

	// DestinationPort The destination port this rule applies to. Set to `null` to allow any destination port. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`, an existing port type firewall alias<br><br>This field is only available when the following conditions are met:<br>- `protocol` must be one of [ tcp, udp, tcp/udp ]<br>
	DestinationPort *string `json:"destination_port"`

	// Direction The direction of traffic this firewall rule applies to. This field only applies to floating firewall rules.<br><br>This field is only available when the following conditions are met:<br>- `floating` must be equal to `true`<br>
	Direction *FirewallRuleDirection `json:"direction,omitempty"`

	// Disabled Enable or disable this firewall rule.<br>
	Disabled *bool `json:"disabled,omitempty"`

	// Dnpipe The name of the traffic shaper limiter pipe or queue to use for incoming traffic.<br>
	Dnpipe *string `json:"dnpipe"`

	// Floating Mark this rule as a floating firewall rule.<br>
	Floating *bool `json:"floating,omitempty"`

	// Gateway The gateway traffic matching this rule will be routed to. Set to `null` to use default.<br>
	Gateway *string `json:"gateway"`

	// Icmptype Th ICMP subtypes this rule applies to. This field is only applicable when `ipprotocol` is `inet` and `protocol` is `icmp`.<br><br>This field is only available when the following conditions are met:<br>- `protocol` must be equal to `'icmp'`<br>
	Icmptype *[]FirewallRuleIcmptype `json:"icmptype,omitempty"`

	// Interface The interface where packets must originate to match this rule.<br>
	Interface *[]string `json:"interface,omitempty"`

	// Ipprotocol The IP version(s) this rule applies to.<br>
	Ipprotocol *FirewallRuleIpprotocol `json:"ipprotocol,omitempty"`

	// Log Enable or disable logging of traffic that matches this rule.<br>
	Log *bool `json:"log,omitempty"`

	// Pdnpipe The name of the traffic shaper limiter pipe or queue to use for outgoing traffic.<br>
	Pdnpipe *string `json:"pdnpipe"`

	// Protocol The IP/transport protocol this rule should match.<br>
	Protocol *FirewallRuleProtocol `json:"protocol"`

	// Quick Apply this action to traffic that matches this rule immediately. This field only applies to floating firewall rules.<br><br>This field is only available when the following conditions are met:<br>- `floating` must be equal to `true`<br>
	Quick *bool `json:"quick,omitempty"`

	// Sched The name of an existing firewall schedule to assign to this firewall rule.<br>
	Sched *string `json:"sched"`

	// Source The source address this rule applies to. Valid value options are: an existing interface, an IP address, a subnet CIDR, an existing alias, `any`, `(self)`, `l2tp`, `pppoe`. The context of this address can be inverted by prefixing the value with `!`. For interface values, the `:ip`  modifier can be appended to the value to use the interface's IP address instead of its entire subnet.<br>
	Source *string `json:"source,omitempty"`

	// SourcePort The source port this rule applies to. Set to `null` to allow any source port. Valid options are: a TCP/UDP port number, a TCP/UDP port range separated by `:`, an existing port type firewall alias<br><br>This field is only available when the following conditions are met:<br>- `protocol` must be one of [ tcp, udp, tcp/udp ]<br>
	SourcePort *string `json:"source_port"`

	// Statetype The state mechanism to use for this firewall rule.<br>
	Statetype *FirewallRuleStatetype `json:"statetype,omitempty"`

	// Tag A packet matching this rule can be marked and this mark used to match on other NAT/filter rules. It is called <br>
	Tag *string `json:"tag,omitempty"`

	// TcpFlagsAny Allow any TCP flags.<br>
	TcpFlagsAny *bool `json:"tcp_flags_any,omitempty"`

	// TcpFlagsOutOf The TCP flags that can be set for this rule to match.<br><br>This field is only available when the following conditions are met:<br>- `tcp_flags_any` must be equal to `false`<br>
	TcpFlagsOutOf *[]FirewallRuleTcpFlagsOutOf `json:"tcp_flags_out_of"`

	// TcpFlagsSet The TCP flags that must be set for this rule to match.<br><br>This field is only available when the following conditions are met:<br>- `tcp_flags_any` must be equal to `false`<br>
	TcpFlagsSet *[]FirewallRuleTcpFlagsSet `json:"tcp_flags_set"`

	// Tracker The internal tracking ID for this firewall rule.<br>
	Tracker *int `json:"tracker"`

	// Type The action to take against traffic that matches this rule.<br>
	Type *FirewallRuleType `json:"type,omitempty"`

	// UpdatedBy The username and IP of the user who last updated this firewall rule.<br>
	UpdatedBy *string `json:"updated_by"`

	// UpdatedTime The unix timestamp of when this firewall rule was original created.<br>
	UpdatedTime *int `json:"updated_time"`
}

// FirewallRuleDirection The direction of traffic this firewall rule applies to. This field only applies to floating firewall rules.<br><br>This field is only available when the following conditions are met:<br>- `floating` must be equal to `true`<br>
type FirewallRuleDirection string

// FirewallRuleIcmptype defines model for FirewallRule.Icmptype.
type FirewallRuleIcmptype string

// FirewallRuleIpprotocol The IP version(s) this rule applies to.<br>
type FirewallRuleIpprotocol string

// FirewallRuleProtocol The IP/transport protocol this rule should match.<br>
type FirewallRuleProtocol string

// FirewallRuleStatetype The state mechanism to use for this firewall rule.<br>
type FirewallRuleStatetype string

// FirewallRuleTcpFlagsOutOf defines model for FirewallRule.TcpFlagsOutOf.
type FirewallRuleTcpFlagsOutOf string

// FirewallRuleTcpFlagsSet defines model for FirewallRule.TcpFlagsSet.
type FirewallRuleTcpFlagsSet string

// FirewallRuleType The action to take against traffic that matches this rule.<br>
type FirewallRuleType string

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError struct {
	// Links An array of links to resources that are related to this API response.
	Links *map[string]interface{} `json:"_links,omitempty"`

	// Code The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`

	// Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
	Data *ForbiddenError_Data `json:"data,omitempty"`

	// Message The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`

	// ResponseId The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseId *string `json:"response_id,omitempty"`

	// Status The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
}

// ForbiddenErrorData0 defines model for .
type ForbiddenErrorData0 = []map[string]interface{}

// ForbiddenErrorData1 defines model for .
type ForbiddenErrorData1 = map[string]interface{}

// ForbiddenError_Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
type ForbiddenError_Data struct {
	union json.RawMessage
}

// MediaTypeError defines model for MediaTypeError.
type MediaTypeError struct {
	// Links An array of links to resources that are related to this API response.
	Links *map[string]interface{} `json:"_links,omitempty"`

	// Code The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`

	// Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
	Data *MediaTypeError_Data `json:"data,omitempty"`

	// Message The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`

	// ResponseId The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseId *string `json:"response_id,omitempty"`

	// Status The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
}

// MediaTypeErrorData0 defines model for .
type MediaTypeErrorData0 = []map[string]interface{}

// MediaTypeErrorData1 defines model for .
type MediaTypeErrorData1 = map[string]interface{}

// MediaTypeError_Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
type MediaTypeError_Data struct {
	union json.RawMessage
}

// MethodNotAllowedError defines model for MethodNotAllowedError.
type MethodNotAllowedError struct {
	// Links An array of links to resources that are related to this API response.
	Links *map[string]interface{} `json:"_links,omitempty"`

	// Code The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`

	// Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
	Data *MethodNotAllowedError_Data `json:"data,omitempty"`

	// Message The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`

	// ResponseId The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseId *string `json:"response_id,omitempty"`

	// Status The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
}

// MethodNotAllowedErrorData0 defines model for .
type MethodNotAllowedErrorData0 = []map[string]interface{}

// MethodNotAllowedErrorData1 defines model for .
type MethodNotAllowedErrorData1 = map[string]interface{}

// MethodNotAllowedError_Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
type MethodNotAllowedError_Data struct {
	union json.RawMessage
}

// NotAcceptableError defines model for NotAcceptableError.
type NotAcceptableError struct {
	// Links An array of links to resources that are related to this API response.
	Links *map[string]interface{} `json:"_links,omitempty"`

	// Code The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`

	// Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
	Data *NotAcceptableError_Data `json:"data,omitempty"`

	// Message The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`

	// ResponseId The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseId *string `json:"response_id,omitempty"`

	// Status The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
}

// NotAcceptableErrorData0 defines model for .
type NotAcceptableErrorData0 = []map[string]interface{}

// NotAcceptableErrorData1 defines model for .
type NotAcceptableErrorData1 = map[string]interface{}

// NotAcceptableError_Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
type NotAcceptableError_Data struct {
	union json.RawMessage
}

// NotFoundError defines model for NotFoundError.
type NotFoundError struct {
	// Links An array of links to resources that are related to this API response.
	Links *map[string]interface{} `json:"_links,omitempty"`

	// Code The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`

	// Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
	Data *NotFoundError_Data `json:"data,omitempty"`

	// Message The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`

	// ResponseId The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseId *string `json:"response_id,omitempty"`

	// Status The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
}

// NotFoundErrorData0 defines model for .
type NotFoundErrorData0 = []map[string]interface{}

// NotFoundErrorData1 defines model for .
type NotFoundErrorData1 = map[string]interface{}

// NotFoundError_Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
type NotFoundError_Data struct {
	union json.RawMessage
}

// ServerError defines model for ServerError.
type ServerError struct {
	// Links An array of links to resources that are related to this API response.
	Links *map[string]interface{} `json:"_links,omitempty"`

	// Code The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`

	// Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
	Data *ServerError_Data `json:"data,omitempty"`

	// Message The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`

	// ResponseId The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseId *string `json:"response_id,omitempty"`

	// Status The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
}

// ServerErrorData0 defines model for .
type ServerErrorData0 = []map[string]interface{}

// ServerErrorData1 defines model for .
type ServerErrorData1 = map[string]interface{}

// ServerError_Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
type ServerError_Data struct {
	union json.RawMessage
}

// ServiceUnavailableError defines model for ServiceUnavailableError.
type ServiceUnavailableError struct {
	// Links An array of links to resources that are related to this API response.
	Links *map[string]interface{} `json:"_links,omitempty"`

	// Code The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`

	// Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
	Data *ServiceUnavailableError_Data `json:"data,omitempty"`

	// Message The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`

	// ResponseId The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseId *string `json:"response_id,omitempty"`

	// Status The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
}

// ServiceUnavailableErrorData0 defines model for .
type ServiceUnavailableErrorData0 = []map[string]interface{}

// ServiceUnavailableErrorData1 defines model for .
type ServiceUnavailableErrorData1 = map[string]interface{}

// ServiceUnavailableError_Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
type ServiceUnavailableError_Data struct {
	union json.RawMessage
}

// Success defines model for Success.
type Success struct {
	// Links An array of links to resources that are related to this API response.
	Links *map[string]interface{} `json:"_links,omitempty"`

	// Code The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`

	// Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
	Data *Success_Data `json:"data,omitempty"`

	// Message The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`

	// ResponseId The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseId *string `json:"response_id,omitempty"`

	// Status The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
}

// SuccessData0 defines model for .
type SuccessData0 = []map[string]interface{}

// SuccessData1 defines model for .
type SuccessData1 = map[string]interface{}

// Success_Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
type Success_Data struct {
	union json.RawMessage
}

// UnprocessableContentError defines model for UnprocessableContentError.
type UnprocessableContentError struct {
	// Links An array of links to resources that are related to this API response.
	Links *map[string]interface{} `json:"_links,omitempty"`

	// Code The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`

	// Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
	Data *UnprocessableContentError_Data `json:"data,omitempty"`

	// Message The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`

	// ResponseId The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseId *string `json:"response_id,omitempty"`

	// Status The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
}

// UnprocessableContentErrorData0 defines model for .
type UnprocessableContentErrorData0 = []map[string]interface{}

// UnprocessableContentErrorData1 defines model for .
type UnprocessableContentErrorData1 = map[string]interface{}

// UnprocessableContentError_Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
type UnprocessableContentError_Data struct {
	union json.RawMessage
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	// Links An array of links to resources that are related to this API response.
	Links *map[string]interface{} `json:"_links,omitempty"`

	// Code The HTTP status code that corresponds with the API response.
	Code *int `json:"code,omitempty"`

	// Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
	Data *ValidationError_Data `json:"data,omitempty"`

	// Message The descriptive message detailing the results of the API call.
	Message *string `json:"message,omitempty"`

	// ResponseId The unique response ID that corresponds with the result of the APIcall. In most situations, this will contain an error code.
	ResponseId *string `json:"response_id,omitempty"`

	// Status The HTTP status message that corresponds with the HTTP status code.
	Status *string `json:"status,omitempty"`
}

// ValidationErrorData0 defines model for .
type ValidationErrorData0 = []map[string]interface{}

// ValidationErrorData1 defines model for .
type ValidationErrorData1 = map[string]interface{}

// ValidationError_Data The data requested from the API. In the event that many objects havebeen requested, this field will be an array of objects. Otherwise, it will only returnthe single object requested.
type ValidationError_Data struct {
	union json.RawMessage
}

// GetFirewallRuleEndpointParams defines parameters for GetFirewallRuleEndpoint.
type GetFirewallRuleEndpointParams struct {
	// Id The ID of the object to target.
	Id struct {
		union json.RawMessage
	} `form:"id" json:"id"`
}

// GetFirewallRuleEndpointParamsId0 defines parameters for GetFirewallRuleEndpoint.
type GetFirewallRuleEndpointParamsId0 = int

// GetFirewallRuleEndpointParamsId1 defines parameters for GetFirewallRuleEndpoint.
type GetFirewallRuleEndpointParamsId1 = string

// AsAuthenticationErrorData0 returns the union data inside the AuthenticationError_Data as a AuthenticationErrorData0
func (t AuthenticationError_Data) AsAuthenticationErrorData0() (AuthenticationErrorData0, error) {
	var body AuthenticationErrorData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAuthenticationErrorData0 overwrites any union data inside the AuthenticationError_Data as the provided AuthenticationErrorData0
func (t *AuthenticationError_Data) FromAuthenticationErrorData0(v AuthenticationErrorData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAuthenticationErrorData0 performs a merge with any union data inside the AuthenticationError_Data, using the provided AuthenticationErrorData0
func (t *AuthenticationError_Data) MergeAuthenticationErrorData0(v AuthenticationErrorData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAuthenticationErrorData1 returns the union data inside the AuthenticationError_Data as a AuthenticationErrorData1
func (t AuthenticationError_Data) AsAuthenticationErrorData1() (AuthenticationErrorData1, error) {
	var body AuthenticationErrorData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAuthenticationErrorData1 overwrites any union data inside the AuthenticationError_Data as the provided AuthenticationErrorData1
func (t *AuthenticationError_Data) FromAuthenticationErrorData1(v AuthenticationErrorData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAuthenticationErrorData1 performs a merge with any union data inside the AuthenticationError_Data, using the provided AuthenticationErrorData1
func (t *AuthenticationError_Data) MergeAuthenticationErrorData1(v AuthenticationErrorData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AuthenticationError_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AuthenticationError_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsConflictErrorData0 returns the union data inside the ConflictError_Data as a ConflictErrorData0
func (t ConflictError_Data) AsConflictErrorData0() (ConflictErrorData0, error) {
	var body ConflictErrorData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConflictErrorData0 overwrites any union data inside the ConflictError_Data as the provided ConflictErrorData0
func (t *ConflictError_Data) FromConflictErrorData0(v ConflictErrorData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConflictErrorData0 performs a merge with any union data inside the ConflictError_Data, using the provided ConflictErrorData0
func (t *ConflictError_Data) MergeConflictErrorData0(v ConflictErrorData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConflictErrorData1 returns the union data inside the ConflictError_Data as a ConflictErrorData1
func (t ConflictError_Data) AsConflictErrorData1() (ConflictErrorData1, error) {
	var body ConflictErrorData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConflictErrorData1 overwrites any union data inside the ConflictError_Data as the provided ConflictErrorData1
func (t *ConflictError_Data) FromConflictErrorData1(v ConflictErrorData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConflictErrorData1 performs a merge with any union data inside the ConflictError_Data, using the provided ConflictErrorData1
func (t *ConflictError_Data) MergeConflictErrorData1(v ConflictErrorData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ConflictError_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ConflictError_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsFailedDependencyErrorData0 returns the union data inside the FailedDependencyError_Data as a FailedDependencyErrorData0
func (t FailedDependencyError_Data) AsFailedDependencyErrorData0() (FailedDependencyErrorData0, error) {
	var body FailedDependencyErrorData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFailedDependencyErrorData0 overwrites any union data inside the FailedDependencyError_Data as the provided FailedDependencyErrorData0
func (t *FailedDependencyError_Data) FromFailedDependencyErrorData0(v FailedDependencyErrorData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFailedDependencyErrorData0 performs a merge with any union data inside the FailedDependencyError_Data, using the provided FailedDependencyErrorData0
func (t *FailedDependencyError_Data) MergeFailedDependencyErrorData0(v FailedDependencyErrorData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFailedDependencyErrorData1 returns the union data inside the FailedDependencyError_Data as a FailedDependencyErrorData1
func (t FailedDependencyError_Data) AsFailedDependencyErrorData1() (FailedDependencyErrorData1, error) {
	var body FailedDependencyErrorData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFailedDependencyErrorData1 overwrites any union data inside the FailedDependencyError_Data as the provided FailedDependencyErrorData1
func (t *FailedDependencyError_Data) FromFailedDependencyErrorData1(v FailedDependencyErrorData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFailedDependencyErrorData1 performs a merge with any union data inside the FailedDependencyError_Data, using the provided FailedDependencyErrorData1
func (t *FailedDependencyError_Data) MergeFailedDependencyErrorData1(v FailedDependencyErrorData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FailedDependencyError_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *FailedDependencyError_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsForbiddenErrorData0 returns the union data inside the ForbiddenError_Data as a ForbiddenErrorData0
func (t ForbiddenError_Data) AsForbiddenErrorData0() (ForbiddenErrorData0, error) {
	var body ForbiddenErrorData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromForbiddenErrorData0 overwrites any union data inside the ForbiddenError_Data as the provided ForbiddenErrorData0
func (t *ForbiddenError_Data) FromForbiddenErrorData0(v ForbiddenErrorData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeForbiddenErrorData0 performs a merge with any union data inside the ForbiddenError_Data, using the provided ForbiddenErrorData0
func (t *ForbiddenError_Data) MergeForbiddenErrorData0(v ForbiddenErrorData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsForbiddenErrorData1 returns the union data inside the ForbiddenError_Data as a ForbiddenErrorData1
func (t ForbiddenError_Data) AsForbiddenErrorData1() (ForbiddenErrorData1, error) {
	var body ForbiddenErrorData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromForbiddenErrorData1 overwrites any union data inside the ForbiddenError_Data as the provided ForbiddenErrorData1
func (t *ForbiddenError_Data) FromForbiddenErrorData1(v ForbiddenErrorData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeForbiddenErrorData1 performs a merge with any union data inside the ForbiddenError_Data, using the provided ForbiddenErrorData1
func (t *ForbiddenError_Data) MergeForbiddenErrorData1(v ForbiddenErrorData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ForbiddenError_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ForbiddenError_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMediaTypeErrorData0 returns the union data inside the MediaTypeError_Data as a MediaTypeErrorData0
func (t MediaTypeError_Data) AsMediaTypeErrorData0() (MediaTypeErrorData0, error) {
	var body MediaTypeErrorData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMediaTypeErrorData0 overwrites any union data inside the MediaTypeError_Data as the provided MediaTypeErrorData0
func (t *MediaTypeError_Data) FromMediaTypeErrorData0(v MediaTypeErrorData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMediaTypeErrorData0 performs a merge with any union data inside the MediaTypeError_Data, using the provided MediaTypeErrorData0
func (t *MediaTypeError_Data) MergeMediaTypeErrorData0(v MediaTypeErrorData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMediaTypeErrorData1 returns the union data inside the MediaTypeError_Data as a MediaTypeErrorData1
func (t MediaTypeError_Data) AsMediaTypeErrorData1() (MediaTypeErrorData1, error) {
	var body MediaTypeErrorData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMediaTypeErrorData1 overwrites any union data inside the MediaTypeError_Data as the provided MediaTypeErrorData1
func (t *MediaTypeError_Data) FromMediaTypeErrorData1(v MediaTypeErrorData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMediaTypeErrorData1 performs a merge with any union data inside the MediaTypeError_Data, using the provided MediaTypeErrorData1
func (t *MediaTypeError_Data) MergeMediaTypeErrorData1(v MediaTypeErrorData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MediaTypeError_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MediaTypeError_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMethodNotAllowedErrorData0 returns the union data inside the MethodNotAllowedError_Data as a MethodNotAllowedErrorData0
func (t MethodNotAllowedError_Data) AsMethodNotAllowedErrorData0() (MethodNotAllowedErrorData0, error) {
	var body MethodNotAllowedErrorData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMethodNotAllowedErrorData0 overwrites any union data inside the MethodNotAllowedError_Data as the provided MethodNotAllowedErrorData0
func (t *MethodNotAllowedError_Data) FromMethodNotAllowedErrorData0(v MethodNotAllowedErrorData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMethodNotAllowedErrorData0 performs a merge with any union data inside the MethodNotAllowedError_Data, using the provided MethodNotAllowedErrorData0
func (t *MethodNotAllowedError_Data) MergeMethodNotAllowedErrorData0(v MethodNotAllowedErrorData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMethodNotAllowedErrorData1 returns the union data inside the MethodNotAllowedError_Data as a MethodNotAllowedErrorData1
func (t MethodNotAllowedError_Data) AsMethodNotAllowedErrorData1() (MethodNotAllowedErrorData1, error) {
	var body MethodNotAllowedErrorData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMethodNotAllowedErrorData1 overwrites any union data inside the MethodNotAllowedError_Data as the provided MethodNotAllowedErrorData1
func (t *MethodNotAllowedError_Data) FromMethodNotAllowedErrorData1(v MethodNotAllowedErrorData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMethodNotAllowedErrorData1 performs a merge with any union data inside the MethodNotAllowedError_Data, using the provided MethodNotAllowedErrorData1
func (t *MethodNotAllowedError_Data) MergeMethodNotAllowedErrorData1(v MethodNotAllowedErrorData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MethodNotAllowedError_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MethodNotAllowedError_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsNotAcceptableErrorData0 returns the union data inside the NotAcceptableError_Data as a NotAcceptableErrorData0
func (t NotAcceptableError_Data) AsNotAcceptableErrorData0() (NotAcceptableErrorData0, error) {
	var body NotAcceptableErrorData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNotAcceptableErrorData0 overwrites any union data inside the NotAcceptableError_Data as the provided NotAcceptableErrorData0
func (t *NotAcceptableError_Data) FromNotAcceptableErrorData0(v NotAcceptableErrorData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNotAcceptableErrorData0 performs a merge with any union data inside the NotAcceptableError_Data, using the provided NotAcceptableErrorData0
func (t *NotAcceptableError_Data) MergeNotAcceptableErrorData0(v NotAcceptableErrorData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNotAcceptableErrorData1 returns the union data inside the NotAcceptableError_Data as a NotAcceptableErrorData1
func (t NotAcceptableError_Data) AsNotAcceptableErrorData1() (NotAcceptableErrorData1, error) {
	var body NotAcceptableErrorData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNotAcceptableErrorData1 overwrites any union data inside the NotAcceptableError_Data as the provided NotAcceptableErrorData1
func (t *NotAcceptableError_Data) FromNotAcceptableErrorData1(v NotAcceptableErrorData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNotAcceptableErrorData1 performs a merge with any union data inside the NotAcceptableError_Data, using the provided NotAcceptableErrorData1
func (t *NotAcceptableError_Data) MergeNotAcceptableErrorData1(v NotAcceptableErrorData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NotAcceptableError_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NotAcceptableError_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsNotFoundErrorData0 returns the union data inside the NotFoundError_Data as a NotFoundErrorData0
func (t NotFoundError_Data) AsNotFoundErrorData0() (NotFoundErrorData0, error) {
	var body NotFoundErrorData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNotFoundErrorData0 overwrites any union data inside the NotFoundError_Data as the provided NotFoundErrorData0
func (t *NotFoundError_Data) FromNotFoundErrorData0(v NotFoundErrorData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNotFoundErrorData0 performs a merge with any union data inside the NotFoundError_Data, using the provided NotFoundErrorData0
func (t *NotFoundError_Data) MergeNotFoundErrorData0(v NotFoundErrorData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNotFoundErrorData1 returns the union data inside the NotFoundError_Data as a NotFoundErrorData1
func (t NotFoundError_Data) AsNotFoundErrorData1() (NotFoundErrorData1, error) {
	var body NotFoundErrorData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNotFoundErrorData1 overwrites any union data inside the NotFoundError_Data as the provided NotFoundErrorData1
func (t *NotFoundError_Data) FromNotFoundErrorData1(v NotFoundErrorData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNotFoundErrorData1 performs a merge with any union data inside the NotFoundError_Data, using the provided NotFoundErrorData1
func (t *NotFoundError_Data) MergeNotFoundErrorData1(v NotFoundErrorData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t NotFoundError_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *NotFoundError_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsServerErrorData0 returns the union data inside the ServerError_Data as a ServerErrorData0
func (t ServerError_Data) AsServerErrorData0() (ServerErrorData0, error) {
	var body ServerErrorData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServerErrorData0 overwrites any union data inside the ServerError_Data as the provided ServerErrorData0
func (t *ServerError_Data) FromServerErrorData0(v ServerErrorData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServerErrorData0 performs a merge with any union data inside the ServerError_Data, using the provided ServerErrorData0
func (t *ServerError_Data) MergeServerErrorData0(v ServerErrorData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsServerErrorData1 returns the union data inside the ServerError_Data as a ServerErrorData1
func (t ServerError_Data) AsServerErrorData1() (ServerErrorData1, error) {
	var body ServerErrorData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServerErrorData1 overwrites any union data inside the ServerError_Data as the provided ServerErrorData1
func (t *ServerError_Data) FromServerErrorData1(v ServerErrorData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServerErrorData1 performs a merge with any union data inside the ServerError_Data, using the provided ServerErrorData1
func (t *ServerError_Data) MergeServerErrorData1(v ServerErrorData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ServerError_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ServerError_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsServiceUnavailableErrorData0 returns the union data inside the ServiceUnavailableError_Data as a ServiceUnavailableErrorData0
func (t ServiceUnavailableError_Data) AsServiceUnavailableErrorData0() (ServiceUnavailableErrorData0, error) {
	var body ServiceUnavailableErrorData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServiceUnavailableErrorData0 overwrites any union data inside the ServiceUnavailableError_Data as the provided ServiceUnavailableErrorData0
func (t *ServiceUnavailableError_Data) FromServiceUnavailableErrorData0(v ServiceUnavailableErrorData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServiceUnavailableErrorData0 performs a merge with any union data inside the ServiceUnavailableError_Data, using the provided ServiceUnavailableErrorData0
func (t *ServiceUnavailableError_Data) MergeServiceUnavailableErrorData0(v ServiceUnavailableErrorData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsServiceUnavailableErrorData1 returns the union data inside the ServiceUnavailableError_Data as a ServiceUnavailableErrorData1
func (t ServiceUnavailableError_Data) AsServiceUnavailableErrorData1() (ServiceUnavailableErrorData1, error) {
	var body ServiceUnavailableErrorData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServiceUnavailableErrorData1 overwrites any union data inside the ServiceUnavailableError_Data as the provided ServiceUnavailableErrorData1
func (t *ServiceUnavailableError_Data) FromServiceUnavailableErrorData1(v ServiceUnavailableErrorData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServiceUnavailableErrorData1 performs a merge with any union data inside the ServiceUnavailableError_Data, using the provided ServiceUnavailableErrorData1
func (t *ServiceUnavailableError_Data) MergeServiceUnavailableErrorData1(v ServiceUnavailableErrorData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ServiceUnavailableError_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ServiceUnavailableError_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSuccessData0 returns the union data inside the Success_Data as a SuccessData0
func (t Success_Data) AsSuccessData0() (SuccessData0, error) {
	var body SuccessData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSuccessData0 overwrites any union data inside the Success_Data as the provided SuccessData0
func (t *Success_Data) FromSuccessData0(v SuccessData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSuccessData0 performs a merge with any union data inside the Success_Data, using the provided SuccessData0
func (t *Success_Data) MergeSuccessData0(v SuccessData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSuccessData1 returns the union data inside the Success_Data as a SuccessData1
func (t Success_Data) AsSuccessData1() (SuccessData1, error) {
	var body SuccessData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSuccessData1 overwrites any union data inside the Success_Data as the provided SuccessData1
func (t *Success_Data) FromSuccessData1(v SuccessData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSuccessData1 performs a merge with any union data inside the Success_Data, using the provided SuccessData1
func (t *Success_Data) MergeSuccessData1(v SuccessData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Success_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Success_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsUnprocessableContentErrorData0 returns the union data inside the UnprocessableContentError_Data as a UnprocessableContentErrorData0
func (t UnprocessableContentError_Data) AsUnprocessableContentErrorData0() (UnprocessableContentErrorData0, error) {
	var body UnprocessableContentErrorData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnprocessableContentErrorData0 overwrites any union data inside the UnprocessableContentError_Data as the provided UnprocessableContentErrorData0
func (t *UnprocessableContentError_Data) FromUnprocessableContentErrorData0(v UnprocessableContentErrorData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnprocessableContentErrorData0 performs a merge with any union data inside the UnprocessableContentError_Data, using the provided UnprocessableContentErrorData0
func (t *UnprocessableContentError_Data) MergeUnprocessableContentErrorData0(v UnprocessableContentErrorData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUnprocessableContentErrorData1 returns the union data inside the UnprocessableContentError_Data as a UnprocessableContentErrorData1
func (t UnprocessableContentError_Data) AsUnprocessableContentErrorData1() (UnprocessableContentErrorData1, error) {
	var body UnprocessableContentErrorData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnprocessableContentErrorData1 overwrites any union data inside the UnprocessableContentError_Data as the provided UnprocessableContentErrorData1
func (t *UnprocessableContentError_Data) FromUnprocessableContentErrorData1(v UnprocessableContentErrorData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnprocessableContentErrorData1 performs a merge with any union data inside the UnprocessableContentError_Data, using the provided UnprocessableContentErrorData1
func (t *UnprocessableContentError_Data) MergeUnprocessableContentErrorData1(v UnprocessableContentErrorData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t UnprocessableContentError_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *UnprocessableContentError_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsValidationErrorData0 returns the union data inside the ValidationError_Data as a ValidationErrorData0
func (t ValidationError_Data) AsValidationErrorData0() (ValidationErrorData0, error) {
	var body ValidationErrorData0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorData0 overwrites any union data inside the ValidationError_Data as the provided ValidationErrorData0
func (t *ValidationError_Data) FromValidationErrorData0(v ValidationErrorData0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorData0 performs a merge with any union data inside the ValidationError_Data, using the provided ValidationErrorData0
func (t *ValidationError_Data) MergeValidationErrorData0(v ValidationErrorData0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorData1 returns the union data inside the ValidationError_Data as a ValidationErrorData1
func (t ValidationError_Data) AsValidationErrorData1() (ValidationErrorData1, error) {
	var body ValidationErrorData1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorData1 overwrites any union data inside the ValidationError_Data as the provided ValidationErrorData1
func (t *ValidationError_Data) FromValidationErrorData1(v ValidationErrorData1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorData1 performs a merge with any union data inside the ValidationError_Data, using the provided ValidationErrorData1
func (t *ValidationError_Data) MergeValidationErrorData1(v ValidationErrorData1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
