// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/libvirt/libvirt/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type CloudinitDisk struct {
	pulumi.CustomResourceState

	CloudinitDiskId pulumi.StringOutput    `pulumi:"cloudinitDiskId"`
	MetaData        pulumi.StringPtrOutput `pulumi:"metaData"`
	Name            pulumi.StringOutput    `pulumi:"name"`
	NetworkConfig   pulumi.StringPtrOutput `pulumi:"networkConfig"`
	Pool            pulumi.StringPtrOutput `pulumi:"pool"`
	UserData        pulumi.StringPtrOutput `pulumi:"userData"`
}

// NewCloudinitDisk registers a new resource with the given unique name, arguments, and options.
func NewCloudinitDisk(ctx *pulumi.Context,
	name string, args *CloudinitDiskArgs, opts ...pulumi.ResourceOption) (*CloudinitDisk, error) {
	if args == nil {
		args = &CloudinitDiskArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource CloudinitDisk
	err = ctx.RegisterPackageResource("libvirt:index/cloudinitDisk:CloudinitDisk", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCloudinitDisk gets an existing CloudinitDisk resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCloudinitDisk(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CloudinitDiskState, opts ...pulumi.ResourceOption) (*CloudinitDisk, error) {
	var resource CloudinitDisk
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("libvirt:index/cloudinitDisk:CloudinitDisk", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CloudinitDisk resources.
type cloudinitDiskState struct {
	CloudinitDiskId *string `pulumi:"cloudinitDiskId"`
	MetaData        *string `pulumi:"metaData"`
	Name            *string `pulumi:"name"`
	NetworkConfig   *string `pulumi:"networkConfig"`
	Pool            *string `pulumi:"pool"`
	UserData        *string `pulumi:"userData"`
}

type CloudinitDiskState struct {
	CloudinitDiskId pulumi.StringPtrInput
	MetaData        pulumi.StringPtrInput
	Name            pulumi.StringPtrInput
	NetworkConfig   pulumi.StringPtrInput
	Pool            pulumi.StringPtrInput
	UserData        pulumi.StringPtrInput
}

func (CloudinitDiskState) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudinitDiskState)(nil)).Elem()
}

type cloudinitDiskArgs struct {
	CloudinitDiskId *string `pulumi:"cloudinitDiskId"`
	MetaData        *string `pulumi:"metaData"`
	Name            *string `pulumi:"name"`
	NetworkConfig   *string `pulumi:"networkConfig"`
	Pool            *string `pulumi:"pool"`
	UserData        *string `pulumi:"userData"`
}

// The set of arguments for constructing a CloudinitDisk resource.
type CloudinitDiskArgs struct {
	CloudinitDiskId pulumi.StringPtrInput
	MetaData        pulumi.StringPtrInput
	Name            pulumi.StringPtrInput
	NetworkConfig   pulumi.StringPtrInput
	Pool            pulumi.StringPtrInput
	UserData        pulumi.StringPtrInput
}

func (CloudinitDiskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudinitDiskArgs)(nil)).Elem()
}

type CloudinitDiskInput interface {
	pulumi.Input

	ToCloudinitDiskOutput() CloudinitDiskOutput
	ToCloudinitDiskOutputWithContext(ctx context.Context) CloudinitDiskOutput
}

func (*CloudinitDisk) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudinitDisk)(nil)).Elem()
}

func (i *CloudinitDisk) ToCloudinitDiskOutput() CloudinitDiskOutput {
	return i.ToCloudinitDiskOutputWithContext(context.Background())
}

func (i *CloudinitDisk) ToCloudinitDiskOutputWithContext(ctx context.Context) CloudinitDiskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudinitDiskOutput)
}

type CloudinitDiskOutput struct{ *pulumi.OutputState }

func (CloudinitDiskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudinitDisk)(nil)).Elem()
}

func (o CloudinitDiskOutput) ToCloudinitDiskOutput() CloudinitDiskOutput {
	return o
}

func (o CloudinitDiskOutput) ToCloudinitDiskOutputWithContext(ctx context.Context) CloudinitDiskOutput {
	return o
}

func (o CloudinitDiskOutput) CloudinitDiskId() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudinitDisk) pulumi.StringOutput { return v.CloudinitDiskId }).(pulumi.StringOutput)
}

func (o CloudinitDiskOutput) MetaData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CloudinitDisk) pulumi.StringPtrOutput { return v.MetaData }).(pulumi.StringPtrOutput)
}

func (o CloudinitDiskOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudinitDisk) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o CloudinitDiskOutput) NetworkConfig() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CloudinitDisk) pulumi.StringPtrOutput { return v.NetworkConfig }).(pulumi.StringPtrOutput)
}

func (o CloudinitDiskOutput) Pool() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CloudinitDisk) pulumi.StringPtrOutput { return v.Pool }).(pulumi.StringPtrOutput)
}

func (o CloudinitDiskOutput) UserData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CloudinitDisk) pulumi.StringPtrOutput { return v.UserData }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CloudinitDiskInput)(nil)).Elem(), &CloudinitDisk{})
	pulumi.RegisterOutputType(CloudinitDiskOutput{})
}
