// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/libvirt/libvirt/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Combustion struct {
	pulumi.CustomResourceState

	CombustionId pulumi.StringOutput    `pulumi:"combustionId"`
	Content      pulumi.StringOutput    `pulumi:"content"`
	Name         pulumi.StringOutput    `pulumi:"name"`
	Pool         pulumi.StringPtrOutput `pulumi:"pool"`
}

// NewCombustion registers a new resource with the given unique name, arguments, and options.
func NewCombustion(ctx *pulumi.Context,
	name string, args *CombustionArgs, opts ...pulumi.ResourceOption) (*Combustion, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Content == nil {
		return nil, errors.New("invalid value for required argument 'Content'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Combustion
	err = ctx.RegisterPackageResource("libvirt:index/combustion:Combustion", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCombustion gets an existing Combustion resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCombustion(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CombustionState, opts ...pulumi.ResourceOption) (*Combustion, error) {
	var resource Combustion
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("libvirt:index/combustion:Combustion", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Combustion resources.
type combustionState struct {
	CombustionId *string `pulumi:"combustionId"`
	Content      *string `pulumi:"content"`
	Name         *string `pulumi:"name"`
	Pool         *string `pulumi:"pool"`
}

type CombustionState struct {
	CombustionId pulumi.StringPtrInput
	Content      pulumi.StringPtrInput
	Name         pulumi.StringPtrInput
	Pool         pulumi.StringPtrInput
}

func (CombustionState) ElementType() reflect.Type {
	return reflect.TypeOf((*combustionState)(nil)).Elem()
}

type combustionArgs struct {
	CombustionId *string `pulumi:"combustionId"`
	Content      string  `pulumi:"content"`
	Name         *string `pulumi:"name"`
	Pool         *string `pulumi:"pool"`
}

// The set of arguments for constructing a Combustion resource.
type CombustionArgs struct {
	CombustionId pulumi.StringPtrInput
	Content      pulumi.StringInput
	Name         pulumi.StringPtrInput
	Pool         pulumi.StringPtrInput
}

func (CombustionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*combustionArgs)(nil)).Elem()
}

type CombustionInput interface {
	pulumi.Input

	ToCombustionOutput() CombustionOutput
	ToCombustionOutputWithContext(ctx context.Context) CombustionOutput
}

func (*Combustion) ElementType() reflect.Type {
	return reflect.TypeOf((**Combustion)(nil)).Elem()
}

func (i *Combustion) ToCombustionOutput() CombustionOutput {
	return i.ToCombustionOutputWithContext(context.Background())
}

func (i *Combustion) ToCombustionOutputWithContext(ctx context.Context) CombustionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CombustionOutput)
}

type CombustionOutput struct{ *pulumi.OutputState }

func (CombustionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Combustion)(nil)).Elem()
}

func (o CombustionOutput) ToCombustionOutput() CombustionOutput {
	return o
}

func (o CombustionOutput) ToCombustionOutputWithContext(ctx context.Context) CombustionOutput {
	return o
}

func (o CombustionOutput) CombustionId() pulumi.StringOutput {
	return o.ApplyT(func(v *Combustion) pulumi.StringOutput { return v.CombustionId }).(pulumi.StringOutput)
}

func (o CombustionOutput) Content() pulumi.StringOutput {
	return o.ApplyT(func(v *Combustion) pulumi.StringOutput { return v.Content }).(pulumi.StringOutput)
}

func (o CombustionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Combustion) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o CombustionOutput) Pool() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Combustion) pulumi.StringPtrOutput { return v.Pool }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CombustionInput)(nil)).Elem(), &Combustion{})
	pulumi.RegisterOutputType(CombustionOutput{})
}
