// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/libvirt/libvirt/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Domain struct {
	pulumi.CustomResourceState

	Arch              pulumi.StringOutput               `pulumi:"arch"`
	Autostart         pulumi.BoolOutput                 `pulumi:"autostart"`
	BootDevices       DomainBootDeviceArrayOutput       `pulumi:"bootDevices"`
	Cloudinit         pulumi.StringPtrOutput            `pulumi:"cloudinit"`
	Cmdlines          pulumi.StringMapArrayOutput       `pulumi:"cmdlines"`
	Consoles          DomainConsoleArrayOutput          `pulumi:"consoles"`
	CoreosIgnition    pulumi.StringPtrOutput            `pulumi:"coreosIgnition"`
	Cpu               DomainCpuPtrOutput                `pulumi:"cpu"`
	Description       pulumi.StringPtrOutput            `pulumi:"description"`
	Disks             DomainDiskArrayOutput             `pulumi:"disks"`
	DomainId          pulumi.StringOutput               `pulumi:"domainId"`
	Emulator          pulumi.StringOutput               `pulumi:"emulator"`
	Filesystems       DomainFilesystemArrayOutput       `pulumi:"filesystems"`
	Firmware          pulumi.StringPtrOutput            `pulumi:"firmware"`
	FwCfgName         pulumi.StringPtrOutput            `pulumi:"fwCfgName"`
	Graphics          DomainGraphicsPtrOutput           `pulumi:"graphics"`
	Initrd            pulumi.StringPtrOutput            `pulumi:"initrd"`
	Kernel            pulumi.StringPtrOutput            `pulumi:"kernel"`
	Machine           pulumi.StringOutput               `pulumi:"machine"`
	Memory            pulumi.Float64PtrOutput           `pulumi:"memory"`
	Metadata          pulumi.StringPtrOutput            `pulumi:"metadata"`
	Name              pulumi.StringOutput               `pulumi:"name"`
	NetworkInterfaces DomainNetworkInterfaceArrayOutput `pulumi:"networkInterfaces"`
	Nvram             DomainNvramPtrOutput              `pulumi:"nvram"`
	QemuAgent         pulumi.BoolPtrOutput              `pulumi:"qemuAgent"`
	Running           pulumi.BoolPtrOutput              `pulumi:"running"`
	Timeouts          DomainTimeoutsPtrOutput           `pulumi:"timeouts"`
	Tpm               DomainTpmPtrOutput                `pulumi:"tpm"`
	Type              pulumi.StringPtrOutput            `pulumi:"type"`
	Vcpu              pulumi.Float64PtrOutput           `pulumi:"vcpu"`
	Video             DomainVideoPtrOutput              `pulumi:"video"`
	Xml               DomainXmlPtrOutput                `pulumi:"xml"`
}

// NewDomain registers a new resource with the given unique name, arguments, and options.
func NewDomain(ctx *pulumi.Context,
	name string, args *DomainArgs, opts ...pulumi.ResourceOption) (*Domain, error) {
	if args == nil {
		args = &DomainArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Domain
	err = ctx.RegisterPackageResource("libvirt:index/domain:Domain", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDomain gets an existing Domain resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDomain(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DomainState, opts ...pulumi.ResourceOption) (*Domain, error) {
	var resource Domain
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("libvirt:index/domain:Domain", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Domain resources.
type domainState struct {
	Arch              *string                  `pulumi:"arch"`
	Autostart         *bool                    `pulumi:"autostart"`
	BootDevices       []DomainBootDevice       `pulumi:"bootDevices"`
	Cloudinit         *string                  `pulumi:"cloudinit"`
	Cmdlines          []map[string]string      `pulumi:"cmdlines"`
	Consoles          []DomainConsole          `pulumi:"consoles"`
	CoreosIgnition    *string                  `pulumi:"coreosIgnition"`
	Cpu               *DomainCpu               `pulumi:"cpu"`
	Description       *string                  `pulumi:"description"`
	Disks             []DomainDisk             `pulumi:"disks"`
	DomainId          *string                  `pulumi:"domainId"`
	Emulator          *string                  `pulumi:"emulator"`
	Filesystems       []DomainFilesystem       `pulumi:"filesystems"`
	Firmware          *string                  `pulumi:"firmware"`
	FwCfgName         *string                  `pulumi:"fwCfgName"`
	Graphics          *DomainGraphics          `pulumi:"graphics"`
	Initrd            *string                  `pulumi:"initrd"`
	Kernel            *string                  `pulumi:"kernel"`
	Machine           *string                  `pulumi:"machine"`
	Memory            *float64                 `pulumi:"memory"`
	Metadata          *string                  `pulumi:"metadata"`
	Name              *string                  `pulumi:"name"`
	NetworkInterfaces []DomainNetworkInterface `pulumi:"networkInterfaces"`
	Nvram             *DomainNvram             `pulumi:"nvram"`
	QemuAgent         *bool                    `pulumi:"qemuAgent"`
	Running           *bool                    `pulumi:"running"`
	Timeouts          *DomainTimeouts          `pulumi:"timeouts"`
	Tpm               *DomainTpm               `pulumi:"tpm"`
	Type              *string                  `pulumi:"type"`
	Vcpu              *float64                 `pulumi:"vcpu"`
	Video             *DomainVideo             `pulumi:"video"`
	Xml               *DomainXml               `pulumi:"xml"`
}

type DomainState struct {
	Arch              pulumi.StringPtrInput
	Autostart         pulumi.BoolPtrInput
	BootDevices       DomainBootDeviceArrayInput
	Cloudinit         pulumi.StringPtrInput
	Cmdlines          pulumi.StringMapArrayInput
	Consoles          DomainConsoleArrayInput
	CoreosIgnition    pulumi.StringPtrInput
	Cpu               DomainCpuPtrInput
	Description       pulumi.StringPtrInput
	Disks             DomainDiskArrayInput
	DomainId          pulumi.StringPtrInput
	Emulator          pulumi.StringPtrInput
	Filesystems       DomainFilesystemArrayInput
	Firmware          pulumi.StringPtrInput
	FwCfgName         pulumi.StringPtrInput
	Graphics          DomainGraphicsPtrInput
	Initrd            pulumi.StringPtrInput
	Kernel            pulumi.StringPtrInput
	Machine           pulumi.StringPtrInput
	Memory            pulumi.Float64PtrInput
	Metadata          pulumi.StringPtrInput
	Name              pulumi.StringPtrInput
	NetworkInterfaces DomainNetworkInterfaceArrayInput
	Nvram             DomainNvramPtrInput
	QemuAgent         pulumi.BoolPtrInput
	Running           pulumi.BoolPtrInput
	Timeouts          DomainTimeoutsPtrInput
	Tpm               DomainTpmPtrInput
	Type              pulumi.StringPtrInput
	Vcpu              pulumi.Float64PtrInput
	Video             DomainVideoPtrInput
	Xml               DomainXmlPtrInput
}

func (DomainState) ElementType() reflect.Type {
	return reflect.TypeOf((*domainState)(nil)).Elem()
}

type domainArgs struct {
	Arch              *string                  `pulumi:"arch"`
	Autostart         *bool                    `pulumi:"autostart"`
	BootDevices       []DomainBootDevice       `pulumi:"bootDevices"`
	Cloudinit         *string                  `pulumi:"cloudinit"`
	Cmdlines          []map[string]string      `pulumi:"cmdlines"`
	Consoles          []DomainConsole          `pulumi:"consoles"`
	CoreosIgnition    *string                  `pulumi:"coreosIgnition"`
	Cpu               *DomainCpu               `pulumi:"cpu"`
	Description       *string                  `pulumi:"description"`
	Disks             []DomainDisk             `pulumi:"disks"`
	DomainId          *string                  `pulumi:"domainId"`
	Emulator          *string                  `pulumi:"emulator"`
	Filesystems       []DomainFilesystem       `pulumi:"filesystems"`
	Firmware          *string                  `pulumi:"firmware"`
	FwCfgName         *string                  `pulumi:"fwCfgName"`
	Graphics          *DomainGraphics          `pulumi:"graphics"`
	Initrd            *string                  `pulumi:"initrd"`
	Kernel            *string                  `pulumi:"kernel"`
	Machine           *string                  `pulumi:"machine"`
	Memory            *float64                 `pulumi:"memory"`
	Metadata          *string                  `pulumi:"metadata"`
	Name              *string                  `pulumi:"name"`
	NetworkInterfaces []DomainNetworkInterface `pulumi:"networkInterfaces"`
	Nvram             *DomainNvram             `pulumi:"nvram"`
	QemuAgent         *bool                    `pulumi:"qemuAgent"`
	Running           *bool                    `pulumi:"running"`
	Timeouts          *DomainTimeouts          `pulumi:"timeouts"`
	Tpm               *DomainTpm               `pulumi:"tpm"`
	Type              *string                  `pulumi:"type"`
	Vcpu              *float64                 `pulumi:"vcpu"`
	Video             *DomainVideo             `pulumi:"video"`
	Xml               *DomainXml               `pulumi:"xml"`
}

// The set of arguments for constructing a Domain resource.
type DomainArgs struct {
	Arch              pulumi.StringPtrInput
	Autostart         pulumi.BoolPtrInput
	BootDevices       DomainBootDeviceArrayInput
	Cloudinit         pulumi.StringPtrInput
	Cmdlines          pulumi.StringMapArrayInput
	Consoles          DomainConsoleArrayInput
	CoreosIgnition    pulumi.StringPtrInput
	Cpu               DomainCpuPtrInput
	Description       pulumi.StringPtrInput
	Disks             DomainDiskArrayInput
	DomainId          pulumi.StringPtrInput
	Emulator          pulumi.StringPtrInput
	Filesystems       DomainFilesystemArrayInput
	Firmware          pulumi.StringPtrInput
	FwCfgName         pulumi.StringPtrInput
	Graphics          DomainGraphicsPtrInput
	Initrd            pulumi.StringPtrInput
	Kernel            pulumi.StringPtrInput
	Machine           pulumi.StringPtrInput
	Memory            pulumi.Float64PtrInput
	Metadata          pulumi.StringPtrInput
	Name              pulumi.StringPtrInput
	NetworkInterfaces DomainNetworkInterfaceArrayInput
	Nvram             DomainNvramPtrInput
	QemuAgent         pulumi.BoolPtrInput
	Running           pulumi.BoolPtrInput
	Timeouts          DomainTimeoutsPtrInput
	Tpm               DomainTpmPtrInput
	Type              pulumi.StringPtrInput
	Vcpu              pulumi.Float64PtrInput
	Video             DomainVideoPtrInput
	Xml               DomainXmlPtrInput
}

func (DomainArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*domainArgs)(nil)).Elem()
}

type DomainInput interface {
	pulumi.Input

	ToDomainOutput() DomainOutput
	ToDomainOutputWithContext(ctx context.Context) DomainOutput
}

func (*Domain) ElementType() reflect.Type {
	return reflect.TypeOf((**Domain)(nil)).Elem()
}

func (i *Domain) ToDomainOutput() DomainOutput {
	return i.ToDomainOutputWithContext(context.Background())
}

func (i *Domain) ToDomainOutputWithContext(ctx context.Context) DomainOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainOutput)
}

type DomainOutput struct{ *pulumi.OutputState }

func (DomainOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Domain)(nil)).Elem()
}

func (o DomainOutput) ToDomainOutput() DomainOutput {
	return o
}

func (o DomainOutput) ToDomainOutputWithContext(ctx context.Context) DomainOutput {
	return o
}

func (o DomainOutput) Arch() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.Arch }).(pulumi.StringOutput)
}

func (o DomainOutput) Autostart() pulumi.BoolOutput {
	return o.ApplyT(func(v *Domain) pulumi.BoolOutput { return v.Autostart }).(pulumi.BoolOutput)
}

func (o DomainOutput) BootDevices() DomainBootDeviceArrayOutput {
	return o.ApplyT(func(v *Domain) DomainBootDeviceArrayOutput { return v.BootDevices }).(DomainBootDeviceArrayOutput)
}

func (o DomainOutput) Cloudinit() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.Cloudinit }).(pulumi.StringPtrOutput)
}

func (o DomainOutput) Cmdlines() pulumi.StringMapArrayOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringMapArrayOutput { return v.Cmdlines }).(pulumi.StringMapArrayOutput)
}

func (o DomainOutput) Consoles() DomainConsoleArrayOutput {
	return o.ApplyT(func(v *Domain) DomainConsoleArrayOutput { return v.Consoles }).(DomainConsoleArrayOutput)
}

func (o DomainOutput) CoreosIgnition() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.CoreosIgnition }).(pulumi.StringPtrOutput)
}

func (o DomainOutput) Cpu() DomainCpuPtrOutput {
	return o.ApplyT(func(v *Domain) DomainCpuPtrOutput { return v.Cpu }).(DomainCpuPtrOutput)
}

func (o DomainOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o DomainOutput) Disks() DomainDiskArrayOutput {
	return o.ApplyT(func(v *Domain) DomainDiskArrayOutput { return v.Disks }).(DomainDiskArrayOutput)
}

func (o DomainOutput) DomainId() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.DomainId }).(pulumi.StringOutput)
}

func (o DomainOutput) Emulator() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.Emulator }).(pulumi.StringOutput)
}

func (o DomainOutput) Filesystems() DomainFilesystemArrayOutput {
	return o.ApplyT(func(v *Domain) DomainFilesystemArrayOutput { return v.Filesystems }).(DomainFilesystemArrayOutput)
}

func (o DomainOutput) Firmware() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.Firmware }).(pulumi.StringPtrOutput)
}

func (o DomainOutput) FwCfgName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.FwCfgName }).(pulumi.StringPtrOutput)
}

func (o DomainOutput) Graphics() DomainGraphicsPtrOutput {
	return o.ApplyT(func(v *Domain) DomainGraphicsPtrOutput { return v.Graphics }).(DomainGraphicsPtrOutput)
}

func (o DomainOutput) Initrd() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.Initrd }).(pulumi.StringPtrOutput)
}

func (o DomainOutput) Kernel() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.Kernel }).(pulumi.StringPtrOutput)
}

func (o DomainOutput) Machine() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.Machine }).(pulumi.StringOutput)
}

func (o DomainOutput) Memory() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.Float64PtrOutput { return v.Memory }).(pulumi.Float64PtrOutput)
}

func (o DomainOutput) Metadata() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.Metadata }).(pulumi.StringPtrOutput)
}

func (o DomainOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o DomainOutput) NetworkInterfaces() DomainNetworkInterfaceArrayOutput {
	return o.ApplyT(func(v *Domain) DomainNetworkInterfaceArrayOutput { return v.NetworkInterfaces }).(DomainNetworkInterfaceArrayOutput)
}

func (o DomainOutput) Nvram() DomainNvramPtrOutput {
	return o.ApplyT(func(v *Domain) DomainNvramPtrOutput { return v.Nvram }).(DomainNvramPtrOutput)
}

func (o DomainOutput) QemuAgent() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.BoolPtrOutput { return v.QemuAgent }).(pulumi.BoolPtrOutput)
}

func (o DomainOutput) Running() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.BoolPtrOutput { return v.Running }).(pulumi.BoolPtrOutput)
}

func (o DomainOutput) Timeouts() DomainTimeoutsPtrOutput {
	return o.ApplyT(func(v *Domain) DomainTimeoutsPtrOutput { return v.Timeouts }).(DomainTimeoutsPtrOutput)
}

func (o DomainOutput) Tpm() DomainTpmPtrOutput {
	return o.ApplyT(func(v *Domain) DomainTpmPtrOutput { return v.Tpm }).(DomainTpmPtrOutput)
}

func (o DomainOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.Type }).(pulumi.StringPtrOutput)
}

func (o DomainOutput) Vcpu() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.Float64PtrOutput { return v.Vcpu }).(pulumi.Float64PtrOutput)
}

func (o DomainOutput) Video() DomainVideoPtrOutput {
	return o.ApplyT(func(v *Domain) DomainVideoPtrOutput { return v.Video }).(DomainVideoPtrOutput)
}

func (o DomainOutput) Xml() DomainXmlPtrOutput {
	return o.ApplyT(func(v *Domain) DomainXmlPtrOutput { return v.Xml }).(DomainXmlPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DomainInput)(nil)).Elem(), &Domain{})
	pulumi.RegisterOutputType(DomainOutput{})
}
