// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/libvirt/libvirt/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetNodeDevices(ctx *pulumi.Context, args *GetNodeDevicesArgs, opts ...pulumi.InvokeOption) (*GetNodeDevicesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetNodeDevicesResult
	err = ctx.InvokePackage("libvirt:index/getNodeDevices:getNodeDevices", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNodeDevices.
type GetNodeDevicesArgs struct {
	Capability *string `pulumi:"capability"`
	Id         *string `pulumi:"id"`
}

// A collection of values returned by getNodeDevices.
type GetNodeDevicesResult struct {
	Capability *string  `pulumi:"capability"`
	Devices    []string `pulumi:"devices"`
	Id         string   `pulumi:"id"`
}

func GetNodeDevicesOutput(ctx *pulumi.Context, args GetNodeDevicesOutputArgs, opts ...pulumi.InvokeOption) GetNodeDevicesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetNodeDevicesResultOutput, error) {
			args := v.(GetNodeDevicesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetNodeDevicesResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("libvirt:index/getNodeDevices:getNodeDevices", args, GetNodeDevicesResultOutput{}, options).(GetNodeDevicesResultOutput), nil
		}).(GetNodeDevicesResultOutput)
}

// A collection of arguments for invoking getNodeDevices.
type GetNodeDevicesOutputArgs struct {
	Capability pulumi.StringPtrInput `pulumi:"capability"`
	Id         pulumi.StringPtrInput `pulumi:"id"`
}

func (GetNodeDevicesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNodeDevicesArgs)(nil)).Elem()
}

// A collection of values returned by getNodeDevices.
type GetNodeDevicesResultOutput struct{ *pulumi.OutputState }

func (GetNodeDevicesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNodeDevicesResult)(nil)).Elem()
}

func (o GetNodeDevicesResultOutput) ToGetNodeDevicesResultOutput() GetNodeDevicesResultOutput {
	return o
}

func (o GetNodeDevicesResultOutput) ToGetNodeDevicesResultOutputWithContext(ctx context.Context) GetNodeDevicesResultOutput {
	return o
}

func (o GetNodeDevicesResultOutput) Capability() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetNodeDevicesResult) *string { return v.Capability }).(pulumi.StringPtrOutput)
}

func (o GetNodeDevicesResultOutput) Devices() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetNodeDevicesResult) []string { return v.Devices }).(pulumi.StringArrayOutput)
}

func (o GetNodeDevicesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNodeDevicesResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetNodeDevicesResultOutput{})
}
