// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/libvirt/libvirt/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetNetworkDnsmasqOptionsTemplate(ctx *pulumi.Context, args *GetNetworkDnsmasqOptionsTemplateArgs, opts ...pulumi.InvokeOption) (*GetNetworkDnsmasqOptionsTemplateResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetNetworkDnsmasqOptionsTemplateResult
	err = ctx.InvokePackage("libvirt:index/getNetworkDnsmasqOptionsTemplate:getNetworkDnsmasqOptionsTemplate", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetworkDnsmasqOptionsTemplate.
type GetNetworkDnsmasqOptionsTemplateArgs struct {
	Id          *string `pulumi:"id"`
	OptionName  string  `pulumi:"optionName"`
	OptionValue *string `pulumi:"optionValue"`
}

// A collection of values returned by getNetworkDnsmasqOptionsTemplate.
type GetNetworkDnsmasqOptionsTemplateResult struct {
	Id          string            `pulumi:"id"`
	OptionName  string            `pulumi:"optionName"`
	OptionValue *string           `pulumi:"optionValue"`
	Rendered    map[string]string `pulumi:"rendered"`
}

func GetNetworkDnsmasqOptionsTemplateOutput(ctx *pulumi.Context, args GetNetworkDnsmasqOptionsTemplateOutputArgs, opts ...pulumi.InvokeOption) GetNetworkDnsmasqOptionsTemplateResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetNetworkDnsmasqOptionsTemplateResultOutput, error) {
			args := v.(GetNetworkDnsmasqOptionsTemplateArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetNetworkDnsmasqOptionsTemplateResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("libvirt:index/getNetworkDnsmasqOptionsTemplate:getNetworkDnsmasqOptionsTemplate", args, GetNetworkDnsmasqOptionsTemplateResultOutput{}, options).(GetNetworkDnsmasqOptionsTemplateResultOutput), nil
		}).(GetNetworkDnsmasqOptionsTemplateResultOutput)
}

// A collection of arguments for invoking getNetworkDnsmasqOptionsTemplate.
type GetNetworkDnsmasqOptionsTemplateOutputArgs struct {
	Id          pulumi.StringPtrInput `pulumi:"id"`
	OptionName  pulumi.StringInput    `pulumi:"optionName"`
	OptionValue pulumi.StringPtrInput `pulumi:"optionValue"`
}

func (GetNetworkDnsmasqOptionsTemplateOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNetworkDnsmasqOptionsTemplateArgs)(nil)).Elem()
}

// A collection of values returned by getNetworkDnsmasqOptionsTemplate.
type GetNetworkDnsmasqOptionsTemplateResultOutput struct{ *pulumi.OutputState }

func (GetNetworkDnsmasqOptionsTemplateResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNetworkDnsmasqOptionsTemplateResult)(nil)).Elem()
}

func (o GetNetworkDnsmasqOptionsTemplateResultOutput) ToGetNetworkDnsmasqOptionsTemplateResultOutput() GetNetworkDnsmasqOptionsTemplateResultOutput {
	return o
}

func (o GetNetworkDnsmasqOptionsTemplateResultOutput) ToGetNetworkDnsmasqOptionsTemplateResultOutputWithContext(ctx context.Context) GetNetworkDnsmasqOptionsTemplateResultOutput {
	return o
}

func (o GetNetworkDnsmasqOptionsTemplateResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkDnsmasqOptionsTemplateResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetNetworkDnsmasqOptionsTemplateResultOutput) OptionName() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkDnsmasqOptionsTemplateResult) string { return v.OptionName }).(pulumi.StringOutput)
}

func (o GetNetworkDnsmasqOptionsTemplateResultOutput) OptionValue() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetNetworkDnsmasqOptionsTemplateResult) *string { return v.OptionValue }).(pulumi.StringPtrOutput)
}

func (o GetNetworkDnsmasqOptionsTemplateResultOutput) Rendered() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetNetworkDnsmasqOptionsTemplateResult) map[string]string { return v.Rendered }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterOutputType(GetNetworkDnsmasqOptionsTemplateResultOutput{})
}
