// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/libvirt/libvirt/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetNodeInfo(ctx *pulumi.Context, args *GetNodeInfoArgs, opts ...pulumi.InvokeOption) (*GetNodeInfoResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetNodeInfoResult
	err = ctx.InvokePackage("libvirt:index/getNodeInfo:getNodeInfo", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNodeInfo.
type GetNodeInfoArgs struct {
	Id *string `pulumi:"id"`
}

// A collection of values returned by getNodeInfo.
type GetNodeInfoResult struct {
	CpuCoresPerSocket float64 `pulumi:"cpuCoresPerSocket"`
	CpuCoresTotal     float64 `pulumi:"cpuCoresTotal"`
	CpuModel          string  `pulumi:"cpuModel"`
	CpuSockets        float64 `pulumi:"cpuSockets"`
	CpuThreadsPerCore float64 `pulumi:"cpuThreadsPerCore"`
	Id                string  `pulumi:"id"`
	MemoryTotalKb     float64 `pulumi:"memoryTotalKb"`
	NumaNodes         float64 `pulumi:"numaNodes"`
}

func GetNodeInfoOutput(ctx *pulumi.Context, args GetNodeInfoOutputArgs, opts ...pulumi.InvokeOption) GetNodeInfoResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetNodeInfoResultOutput, error) {
			args := v.(GetNodeInfoArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetNodeInfoResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("libvirt:index/getNodeInfo:getNodeInfo", args, GetNodeInfoResultOutput{}, options).(GetNodeInfoResultOutput), nil
		}).(GetNodeInfoResultOutput)
}

// A collection of arguments for invoking getNodeInfo.
type GetNodeInfoOutputArgs struct {
	Id pulumi.StringPtrInput `pulumi:"id"`
}

func (GetNodeInfoOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNodeInfoArgs)(nil)).Elem()
}

// A collection of values returned by getNodeInfo.
type GetNodeInfoResultOutput struct{ *pulumi.OutputState }

func (GetNodeInfoResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNodeInfoResult)(nil)).Elem()
}

func (o GetNodeInfoResultOutput) ToGetNodeInfoResultOutput() GetNodeInfoResultOutput {
	return o
}

func (o GetNodeInfoResultOutput) ToGetNodeInfoResultOutputWithContext(ctx context.Context) GetNodeInfoResultOutput {
	return o
}

func (o GetNodeInfoResultOutput) CpuCoresPerSocket() pulumi.Float64Output {
	return o.ApplyT(func(v GetNodeInfoResult) float64 { return v.CpuCoresPerSocket }).(pulumi.Float64Output)
}

func (o GetNodeInfoResultOutput) CpuCoresTotal() pulumi.Float64Output {
	return o.ApplyT(func(v GetNodeInfoResult) float64 { return v.CpuCoresTotal }).(pulumi.Float64Output)
}

func (o GetNodeInfoResultOutput) CpuModel() pulumi.StringOutput {
	return o.ApplyT(func(v GetNodeInfoResult) string { return v.CpuModel }).(pulumi.StringOutput)
}

func (o GetNodeInfoResultOutput) CpuSockets() pulumi.Float64Output {
	return o.ApplyT(func(v GetNodeInfoResult) float64 { return v.CpuSockets }).(pulumi.Float64Output)
}

func (o GetNodeInfoResultOutput) CpuThreadsPerCore() pulumi.Float64Output {
	return o.ApplyT(func(v GetNodeInfoResult) float64 { return v.CpuThreadsPerCore }).(pulumi.Float64Output)
}

func (o GetNodeInfoResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNodeInfoResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetNodeInfoResultOutput) MemoryTotalKb() pulumi.Float64Output {
	return o.ApplyT(func(v GetNodeInfoResult) float64 { return v.MemoryTotalKb }).(pulumi.Float64Output)
}

func (o GetNodeInfoResultOutput) NumaNodes() pulumi.Float64Output {
	return o.ApplyT(func(v GetNodeInfoResult) float64 { return v.NumaNodes }).(pulumi.Float64Output)
}

func init() {
	pulumi.RegisterOutputType(GetNodeInfoResultOutput{})
}
