// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/libvirt/libvirt/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetNetworkDnsHostTemplate(ctx *pulumi.Context, args *GetNetworkDnsHostTemplateArgs, opts ...pulumi.InvokeOption) (*GetNetworkDnsHostTemplateResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetNetworkDnsHostTemplateResult
	err = ctx.InvokePackage("libvirt:index/getNetworkDnsHostTemplate:getNetworkDnsHostTemplate", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetworkDnsHostTemplate.
type GetNetworkDnsHostTemplateArgs struct {
	Hostname string  `pulumi:"hostname"`
	Id       *string `pulumi:"id"`
	Ip       string  `pulumi:"ip"`
}

// A collection of values returned by getNetworkDnsHostTemplate.
type GetNetworkDnsHostTemplateResult struct {
	Hostname string            `pulumi:"hostname"`
	Id       string            `pulumi:"id"`
	Ip       string            `pulumi:"ip"`
	Rendered map[string]string `pulumi:"rendered"`
}

func GetNetworkDnsHostTemplateOutput(ctx *pulumi.Context, args GetNetworkDnsHostTemplateOutputArgs, opts ...pulumi.InvokeOption) GetNetworkDnsHostTemplateResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetNetworkDnsHostTemplateResultOutput, error) {
			args := v.(GetNetworkDnsHostTemplateArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetNetworkDnsHostTemplateResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("libvirt:index/getNetworkDnsHostTemplate:getNetworkDnsHostTemplate", args, GetNetworkDnsHostTemplateResultOutput{}, options).(GetNetworkDnsHostTemplateResultOutput), nil
		}).(GetNetworkDnsHostTemplateResultOutput)
}

// A collection of arguments for invoking getNetworkDnsHostTemplate.
type GetNetworkDnsHostTemplateOutputArgs struct {
	Hostname pulumi.StringInput    `pulumi:"hostname"`
	Id       pulumi.StringPtrInput `pulumi:"id"`
	Ip       pulumi.StringInput    `pulumi:"ip"`
}

func (GetNetworkDnsHostTemplateOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNetworkDnsHostTemplateArgs)(nil)).Elem()
}

// A collection of values returned by getNetworkDnsHostTemplate.
type GetNetworkDnsHostTemplateResultOutput struct{ *pulumi.OutputState }

func (GetNetworkDnsHostTemplateResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNetworkDnsHostTemplateResult)(nil)).Elem()
}

func (o GetNetworkDnsHostTemplateResultOutput) ToGetNetworkDnsHostTemplateResultOutput() GetNetworkDnsHostTemplateResultOutput {
	return o
}

func (o GetNetworkDnsHostTemplateResultOutput) ToGetNetworkDnsHostTemplateResultOutputWithContext(ctx context.Context) GetNetworkDnsHostTemplateResultOutput {
	return o
}

func (o GetNetworkDnsHostTemplateResultOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkDnsHostTemplateResult) string { return v.Hostname }).(pulumi.StringOutput)
}

func (o GetNetworkDnsHostTemplateResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkDnsHostTemplateResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetNetworkDnsHostTemplateResultOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkDnsHostTemplateResult) string { return v.Ip }).(pulumi.StringOutput)
}

func (o GetNetworkDnsHostTemplateResultOutput) Rendered() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetNetworkDnsHostTemplateResult) map[string]string { return v.Rendered }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterOutputType(GetNetworkDnsHostTemplateResultOutput{})
}
