// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/libvirt/libvirt/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetNodeDeviceInfo(ctx *pulumi.Context, args *GetNodeDeviceInfoArgs, opts ...pulumi.InvokeOption) (*GetNodeDeviceInfoResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetNodeDeviceInfoResult
	err = ctx.InvokePackage("libvirt:index/getNodeDeviceInfo:getNodeDeviceInfo", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNodeDeviceInfo.
type GetNodeDeviceInfoArgs struct {
	Capability *GetNodeDeviceInfoCapability `pulumi:"capability"`
	Id         *string                      `pulumi:"id"`
	Name       string                       `pulumi:"name"`
}

// A collection of values returned by getNodeDeviceInfo.
type GetNodeDeviceInfoResult struct {
	Capability *GetNodeDeviceInfoCapability `pulumi:"capability"`
	Devnodes   []GetNodeDeviceInfoDevnode   `pulumi:"devnodes"`
	Id         string                       `pulumi:"id"`
	Name       string                       `pulumi:"name"`
	Parent     string                       `pulumi:"parent"`
	Path       string                       `pulumi:"path"`
	Xml        string                       `pulumi:"xml"`
}

func GetNodeDeviceInfoOutput(ctx *pulumi.Context, args GetNodeDeviceInfoOutputArgs, opts ...pulumi.InvokeOption) GetNodeDeviceInfoResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetNodeDeviceInfoResultOutput, error) {
			args := v.(GetNodeDeviceInfoArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetNodeDeviceInfoResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("libvirt:index/getNodeDeviceInfo:getNodeDeviceInfo", args, GetNodeDeviceInfoResultOutput{}, options).(GetNodeDeviceInfoResultOutput), nil
		}).(GetNodeDeviceInfoResultOutput)
}

// A collection of arguments for invoking getNodeDeviceInfo.
type GetNodeDeviceInfoOutputArgs struct {
	Capability GetNodeDeviceInfoCapabilityPtrInput `pulumi:"capability"`
	Id         pulumi.StringPtrInput               `pulumi:"id"`
	Name       pulumi.StringInput                  `pulumi:"name"`
}

func (GetNodeDeviceInfoOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNodeDeviceInfoArgs)(nil)).Elem()
}

// A collection of values returned by getNodeDeviceInfo.
type GetNodeDeviceInfoResultOutput struct{ *pulumi.OutputState }

func (GetNodeDeviceInfoResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNodeDeviceInfoResult)(nil)).Elem()
}

func (o GetNodeDeviceInfoResultOutput) ToGetNodeDeviceInfoResultOutput() GetNodeDeviceInfoResultOutput {
	return o
}

func (o GetNodeDeviceInfoResultOutput) ToGetNodeDeviceInfoResultOutputWithContext(ctx context.Context) GetNodeDeviceInfoResultOutput {
	return o
}

func (o GetNodeDeviceInfoResultOutput) Capability() GetNodeDeviceInfoCapabilityPtrOutput {
	return o.ApplyT(func(v GetNodeDeviceInfoResult) *GetNodeDeviceInfoCapability { return v.Capability }).(GetNodeDeviceInfoCapabilityPtrOutput)
}

func (o GetNodeDeviceInfoResultOutput) Devnodes() GetNodeDeviceInfoDevnodeArrayOutput {
	return o.ApplyT(func(v GetNodeDeviceInfoResult) []GetNodeDeviceInfoDevnode { return v.Devnodes }).(GetNodeDeviceInfoDevnodeArrayOutput)
}

func (o GetNodeDeviceInfoResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNodeDeviceInfoResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetNodeDeviceInfoResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetNodeDeviceInfoResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetNodeDeviceInfoResultOutput) Parent() pulumi.StringOutput {
	return o.ApplyT(func(v GetNodeDeviceInfoResult) string { return v.Parent }).(pulumi.StringOutput)
}

func (o GetNodeDeviceInfoResultOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v GetNodeDeviceInfoResult) string { return v.Path }).(pulumi.StringOutput)
}

func (o GetNodeDeviceInfoResultOutput) Xml() pulumi.StringOutput {
	return o.ApplyT(func(v GetNodeDeviceInfoResult) string { return v.Xml }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetNodeDeviceInfoResultOutput{})
}
