// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/libvirt/libvirt/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Ignition struct {
	pulumi.CustomResourceState

	Content    pulumi.StringOutput    `pulumi:"content"`
	IgnitionId pulumi.StringOutput    `pulumi:"ignitionId"`
	Name       pulumi.StringOutput    `pulumi:"name"`
	Pool       pulumi.StringPtrOutput `pulumi:"pool"`
}

// NewIgnition registers a new resource with the given unique name, arguments, and options.
func NewIgnition(ctx *pulumi.Context,
	name string, args *IgnitionArgs, opts ...pulumi.ResourceOption) (*Ignition, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Content == nil {
		return nil, errors.New("invalid value for required argument 'Content'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Ignition
	err = ctx.RegisterPackageResource("libvirt:index/ignition:Ignition", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIgnition gets an existing Ignition resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIgnition(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IgnitionState, opts ...pulumi.ResourceOption) (*Ignition, error) {
	var resource Ignition
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("libvirt:index/ignition:Ignition", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Ignition resources.
type ignitionState struct {
	Content    *string `pulumi:"content"`
	IgnitionId *string `pulumi:"ignitionId"`
	Name       *string `pulumi:"name"`
	Pool       *string `pulumi:"pool"`
}

type IgnitionState struct {
	Content    pulumi.StringPtrInput
	IgnitionId pulumi.StringPtrInput
	Name       pulumi.StringPtrInput
	Pool       pulumi.StringPtrInput
}

func (IgnitionState) ElementType() reflect.Type {
	return reflect.TypeOf((*ignitionState)(nil)).Elem()
}

type ignitionArgs struct {
	Content    string  `pulumi:"content"`
	IgnitionId *string `pulumi:"ignitionId"`
	Name       *string `pulumi:"name"`
	Pool       *string `pulumi:"pool"`
}

// The set of arguments for constructing a Ignition resource.
type IgnitionArgs struct {
	Content    pulumi.StringInput
	IgnitionId pulumi.StringPtrInput
	Name       pulumi.StringPtrInput
	Pool       pulumi.StringPtrInput
}

func (IgnitionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ignitionArgs)(nil)).Elem()
}

type IgnitionInput interface {
	pulumi.Input

	ToIgnitionOutput() IgnitionOutput
	ToIgnitionOutputWithContext(ctx context.Context) IgnitionOutput
}

func (*Ignition) ElementType() reflect.Type {
	return reflect.TypeOf((**Ignition)(nil)).Elem()
}

func (i *Ignition) ToIgnitionOutput() IgnitionOutput {
	return i.ToIgnitionOutputWithContext(context.Background())
}

func (i *Ignition) ToIgnitionOutputWithContext(ctx context.Context) IgnitionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IgnitionOutput)
}

type IgnitionOutput struct{ *pulumi.OutputState }

func (IgnitionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Ignition)(nil)).Elem()
}

func (o IgnitionOutput) ToIgnitionOutput() IgnitionOutput {
	return o
}

func (o IgnitionOutput) ToIgnitionOutputWithContext(ctx context.Context) IgnitionOutput {
	return o
}

func (o IgnitionOutput) Content() pulumi.StringOutput {
	return o.ApplyT(func(v *Ignition) pulumi.StringOutput { return v.Content }).(pulumi.StringOutput)
}

func (o IgnitionOutput) IgnitionId() pulumi.StringOutput {
	return o.ApplyT(func(v *Ignition) pulumi.StringOutput { return v.IgnitionId }).(pulumi.StringOutput)
}

func (o IgnitionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Ignition) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o IgnitionOutput) Pool() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Ignition) pulumi.StringPtrOutput { return v.Pool }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IgnitionInput)(nil)).Elem(), &Ignition{})
	pulumi.RegisterOutputType(IgnitionOutput{})
}
