// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/libvirt/libvirt/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Network struct {
	pulumi.CustomResourceState

	Addresses      pulumi.StringArrayOutput       `pulumi:"addresses"`
	Autostart      pulumi.BoolOutput              `pulumi:"autostart"`
	Bridge         pulumi.StringOutput            `pulumi:"bridge"`
	Dhcp           NetworkDhcpPtrOutput           `pulumi:"dhcp"`
	Dns            NetworkDnsPtrOutput            `pulumi:"dns"`
	DnsmasqOptions NetworkDnsmasqOptionsPtrOutput `pulumi:"dnsmasqOptions"`
	Domain         pulumi.StringPtrOutput         `pulumi:"domain"`
	Mode           pulumi.StringPtrOutput         `pulumi:"mode"`
	Mtu            pulumi.Float64PtrOutput        `pulumi:"mtu"`
	Name           pulumi.StringOutput            `pulumi:"name"`
	NetworkId      pulumi.StringOutput            `pulumi:"networkId"`
	Routes         NetworkRouteArrayOutput        `pulumi:"routes"`
	Xml            NetworkXmlPtrOutput            `pulumi:"xml"`
}

// NewNetwork registers a new resource with the given unique name, arguments, and options.
func NewNetwork(ctx *pulumi.Context,
	name string, args *NetworkArgs, opts ...pulumi.ResourceOption) (*Network, error) {
	if args == nil {
		args = &NetworkArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Network
	err = ctx.RegisterPackageResource("libvirt:index/network:Network", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetwork gets an existing Network resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetwork(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkState, opts ...pulumi.ResourceOption) (*Network, error) {
	var resource Network
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("libvirt:index/network:Network", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Network resources.
type networkState struct {
	Addresses      []string               `pulumi:"addresses"`
	Autostart      *bool                  `pulumi:"autostart"`
	Bridge         *string                `pulumi:"bridge"`
	Dhcp           *NetworkDhcp           `pulumi:"dhcp"`
	Dns            *NetworkDns            `pulumi:"dns"`
	DnsmasqOptions *NetworkDnsmasqOptions `pulumi:"dnsmasqOptions"`
	Domain         *string                `pulumi:"domain"`
	Mode           *string                `pulumi:"mode"`
	Mtu            *float64               `pulumi:"mtu"`
	Name           *string                `pulumi:"name"`
	NetworkId      *string                `pulumi:"networkId"`
	Routes         []NetworkRoute         `pulumi:"routes"`
	Xml            *NetworkXml            `pulumi:"xml"`
}

type NetworkState struct {
	Addresses      pulumi.StringArrayInput
	Autostart      pulumi.BoolPtrInput
	Bridge         pulumi.StringPtrInput
	Dhcp           NetworkDhcpPtrInput
	Dns            NetworkDnsPtrInput
	DnsmasqOptions NetworkDnsmasqOptionsPtrInput
	Domain         pulumi.StringPtrInput
	Mode           pulumi.StringPtrInput
	Mtu            pulumi.Float64PtrInput
	Name           pulumi.StringPtrInput
	NetworkId      pulumi.StringPtrInput
	Routes         NetworkRouteArrayInput
	Xml            NetworkXmlPtrInput
}

func (NetworkState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkState)(nil)).Elem()
}

type networkArgs struct {
	Addresses      []string               `pulumi:"addresses"`
	Autostart      *bool                  `pulumi:"autostart"`
	Bridge         *string                `pulumi:"bridge"`
	Dhcp           *NetworkDhcp           `pulumi:"dhcp"`
	Dns            *NetworkDns            `pulumi:"dns"`
	DnsmasqOptions *NetworkDnsmasqOptions `pulumi:"dnsmasqOptions"`
	Domain         *string                `pulumi:"domain"`
	Mode           *string                `pulumi:"mode"`
	Mtu            *float64               `pulumi:"mtu"`
	Name           *string                `pulumi:"name"`
	NetworkId      *string                `pulumi:"networkId"`
	Routes         []NetworkRoute         `pulumi:"routes"`
	Xml            *NetworkXml            `pulumi:"xml"`
}

// The set of arguments for constructing a Network resource.
type NetworkArgs struct {
	Addresses      pulumi.StringArrayInput
	Autostart      pulumi.BoolPtrInput
	Bridge         pulumi.StringPtrInput
	Dhcp           NetworkDhcpPtrInput
	Dns            NetworkDnsPtrInput
	DnsmasqOptions NetworkDnsmasqOptionsPtrInput
	Domain         pulumi.StringPtrInput
	Mode           pulumi.StringPtrInput
	Mtu            pulumi.Float64PtrInput
	Name           pulumi.StringPtrInput
	NetworkId      pulumi.StringPtrInput
	Routes         NetworkRouteArrayInput
	Xml            NetworkXmlPtrInput
}

func (NetworkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkArgs)(nil)).Elem()
}

type NetworkInput interface {
	pulumi.Input

	ToNetworkOutput() NetworkOutput
	ToNetworkOutputWithContext(ctx context.Context) NetworkOutput
}

func (*Network) ElementType() reflect.Type {
	return reflect.TypeOf((**Network)(nil)).Elem()
}

func (i *Network) ToNetworkOutput() NetworkOutput {
	return i.ToNetworkOutputWithContext(context.Background())
}

func (i *Network) ToNetworkOutputWithContext(ctx context.Context) NetworkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkOutput)
}

type NetworkOutput struct{ *pulumi.OutputState }

func (NetworkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Network)(nil)).Elem()
}

func (o NetworkOutput) ToNetworkOutput() NetworkOutput {
	return o
}

func (o NetworkOutput) ToNetworkOutputWithContext(ctx context.Context) NetworkOutput {
	return o
}

func (o NetworkOutput) Addresses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Network) pulumi.StringArrayOutput { return v.Addresses }).(pulumi.StringArrayOutput)
}

func (o NetworkOutput) Autostart() pulumi.BoolOutput {
	return o.ApplyT(func(v *Network) pulumi.BoolOutput { return v.Autostart }).(pulumi.BoolOutput)
}

func (o NetworkOutput) Bridge() pulumi.StringOutput {
	return o.ApplyT(func(v *Network) pulumi.StringOutput { return v.Bridge }).(pulumi.StringOutput)
}

func (o NetworkOutput) Dhcp() NetworkDhcpPtrOutput {
	return o.ApplyT(func(v *Network) NetworkDhcpPtrOutput { return v.Dhcp }).(NetworkDhcpPtrOutput)
}

func (o NetworkOutput) Dns() NetworkDnsPtrOutput {
	return o.ApplyT(func(v *Network) NetworkDnsPtrOutput { return v.Dns }).(NetworkDnsPtrOutput)
}

func (o NetworkOutput) DnsmasqOptions() NetworkDnsmasqOptionsPtrOutput {
	return o.ApplyT(func(v *Network) NetworkDnsmasqOptionsPtrOutput { return v.DnsmasqOptions }).(NetworkDnsmasqOptionsPtrOutput)
}

func (o NetworkOutput) Domain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Network) pulumi.StringPtrOutput { return v.Domain }).(pulumi.StringPtrOutput)
}

func (o NetworkOutput) Mode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Network) pulumi.StringPtrOutput { return v.Mode }).(pulumi.StringPtrOutput)
}

func (o NetworkOutput) Mtu() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *Network) pulumi.Float64PtrOutput { return v.Mtu }).(pulumi.Float64PtrOutput)
}

func (o NetworkOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Network) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o NetworkOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v *Network) pulumi.StringOutput { return v.NetworkId }).(pulumi.StringOutput)
}

func (o NetworkOutput) Routes() NetworkRouteArrayOutput {
	return o.ApplyT(func(v *Network) NetworkRouteArrayOutput { return v.Routes }).(NetworkRouteArrayOutput)
}

func (o NetworkOutput) Xml() NetworkXmlPtrOutput {
	return o.ApplyT(func(v *Network) NetworkXmlPtrOutput { return v.Xml }).(NetworkXmlPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkInput)(nil)).Elem(), &Network{})
	pulumi.RegisterOutputType(NetworkOutput{})
}
