// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/libvirt/libvirt/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Pool struct {
	pulumi.CustomResourceState

	Allocation pulumi.Float64Output `pulumi:"allocation"`
	Available  pulumi.Float64Output `pulumi:"available"`
	Capacity   pulumi.Float64Output `pulumi:"capacity"`
	Name       pulumi.StringOutput  `pulumi:"name"`
	// Deprecated: Deprecated
	Path   pulumi.StringPtrOutput `pulumi:"path"`
	PoolId pulumi.StringOutput    `pulumi:"poolId"`
	Source PoolSourcePtrOutput    `pulumi:"source"`
	Target PoolTargetPtrOutput    `pulumi:"target"`
	Type   pulumi.StringOutput    `pulumi:"type"`
	Xml    PoolXmlPtrOutput       `pulumi:"xml"`
}

// NewPool registers a new resource with the given unique name, arguments, and options.
func NewPool(ctx *pulumi.Context,
	name string, args *PoolArgs, opts ...pulumi.ResourceOption) (*Pool, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Pool
	err = ctx.RegisterPackageResource("libvirt:index/pool:Pool", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPool gets an existing Pool resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPool(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PoolState, opts ...pulumi.ResourceOption) (*Pool, error) {
	var resource Pool
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("libvirt:index/pool:Pool", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Pool resources.
type poolState struct {
	Allocation *float64 `pulumi:"allocation"`
	Available  *float64 `pulumi:"available"`
	Capacity   *float64 `pulumi:"capacity"`
	Name       *string  `pulumi:"name"`
	// Deprecated: Deprecated
	Path   *string     `pulumi:"path"`
	PoolId *string     `pulumi:"poolId"`
	Source *PoolSource `pulumi:"source"`
	Target *PoolTarget `pulumi:"target"`
	Type   *string     `pulumi:"type"`
	Xml    *PoolXml    `pulumi:"xml"`
}

type PoolState struct {
	Allocation pulumi.Float64PtrInput
	Available  pulumi.Float64PtrInput
	Capacity   pulumi.Float64PtrInput
	Name       pulumi.StringPtrInput
	// Deprecated: Deprecated
	Path   pulumi.StringPtrInput
	PoolId pulumi.StringPtrInput
	Source PoolSourcePtrInput
	Target PoolTargetPtrInput
	Type   pulumi.StringPtrInput
	Xml    PoolXmlPtrInput
}

func (PoolState) ElementType() reflect.Type {
	return reflect.TypeOf((*poolState)(nil)).Elem()
}

type poolArgs struct {
	Allocation *float64 `pulumi:"allocation"`
	Available  *float64 `pulumi:"available"`
	Capacity   *float64 `pulumi:"capacity"`
	Name       *string  `pulumi:"name"`
	// Deprecated: Deprecated
	Path   *string     `pulumi:"path"`
	PoolId *string     `pulumi:"poolId"`
	Source *PoolSource `pulumi:"source"`
	Target *PoolTarget `pulumi:"target"`
	Type   string      `pulumi:"type"`
	Xml    *PoolXml    `pulumi:"xml"`
}

// The set of arguments for constructing a Pool resource.
type PoolArgs struct {
	Allocation pulumi.Float64PtrInput
	Available  pulumi.Float64PtrInput
	Capacity   pulumi.Float64PtrInput
	Name       pulumi.StringPtrInput
	// Deprecated: Deprecated
	Path   pulumi.StringPtrInput
	PoolId pulumi.StringPtrInput
	Source PoolSourcePtrInput
	Target PoolTargetPtrInput
	Type   pulumi.StringInput
	Xml    PoolXmlPtrInput
}

func (PoolArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*poolArgs)(nil)).Elem()
}

type PoolInput interface {
	pulumi.Input

	ToPoolOutput() PoolOutput
	ToPoolOutputWithContext(ctx context.Context) PoolOutput
}

func (*Pool) ElementType() reflect.Type {
	return reflect.TypeOf((**Pool)(nil)).Elem()
}

func (i *Pool) ToPoolOutput() PoolOutput {
	return i.ToPoolOutputWithContext(context.Background())
}

func (i *Pool) ToPoolOutputWithContext(ctx context.Context) PoolOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PoolOutput)
}

type PoolOutput struct{ *pulumi.OutputState }

func (PoolOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Pool)(nil)).Elem()
}

func (o PoolOutput) ToPoolOutput() PoolOutput {
	return o
}

func (o PoolOutput) ToPoolOutputWithContext(ctx context.Context) PoolOutput {
	return o
}

func (o PoolOutput) Allocation() pulumi.Float64Output {
	return o.ApplyT(func(v *Pool) pulumi.Float64Output { return v.Allocation }).(pulumi.Float64Output)
}

func (o PoolOutput) Available() pulumi.Float64Output {
	return o.ApplyT(func(v *Pool) pulumi.Float64Output { return v.Available }).(pulumi.Float64Output)
}

func (o PoolOutput) Capacity() pulumi.Float64Output {
	return o.ApplyT(func(v *Pool) pulumi.Float64Output { return v.Capacity }).(pulumi.Float64Output)
}

func (o PoolOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Pool) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Deprecated: Deprecated
func (o PoolOutput) Path() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Pool) pulumi.StringPtrOutput { return v.Path }).(pulumi.StringPtrOutput)
}

func (o PoolOutput) PoolId() pulumi.StringOutput {
	return o.ApplyT(func(v *Pool) pulumi.StringOutput { return v.PoolId }).(pulumi.StringOutput)
}

func (o PoolOutput) Source() PoolSourcePtrOutput {
	return o.ApplyT(func(v *Pool) PoolSourcePtrOutput { return v.Source }).(PoolSourcePtrOutput)
}

func (o PoolOutput) Target() PoolTargetPtrOutput {
	return o.ApplyT(func(v *Pool) PoolTargetPtrOutput { return v.Target }).(PoolTargetPtrOutput)
}

func (o PoolOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *Pool) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

func (o PoolOutput) Xml() PoolXmlPtrOutput {
	return o.ApplyT(func(v *Pool) PoolXmlPtrOutput { return v.Xml }).(PoolXmlPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PoolInput)(nil)).Elem(), &Pool{})
	pulumi.RegisterOutputType(PoolOutput{})
}
