// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package libvirt

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/libvirt/libvirt/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Volume struct {
	pulumi.CustomResourceState

	BaseVolumeId   pulumi.StringPtrOutput `pulumi:"baseVolumeId"`
	BaseVolumeName pulumi.StringPtrOutput `pulumi:"baseVolumeName"`
	BaseVolumePool pulumi.StringPtrOutput `pulumi:"baseVolumePool"`
	Format         pulumi.StringOutput    `pulumi:"format"`
	Name           pulumi.StringOutput    `pulumi:"name"`
	Pool           pulumi.StringPtrOutput `pulumi:"pool"`
	Size           pulumi.Float64Output   `pulumi:"size"`
	Source         pulumi.StringPtrOutput `pulumi:"source"`
	VolumeId       pulumi.StringOutput    `pulumi:"volumeId"`
	Xml            VolumeXmlPtrOutput     `pulumi:"xml"`
}

// NewVolume registers a new resource with the given unique name, arguments, and options.
func NewVolume(ctx *pulumi.Context,
	name string, args *VolumeArgs, opts ...pulumi.ResourceOption) (*Volume, error) {
	if args == nil {
		args = &VolumeArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Volume
	err = ctx.RegisterPackageResource("libvirt:index/volume:Volume", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVolume gets an existing Volume resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVolume(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VolumeState, opts ...pulumi.ResourceOption) (*Volume, error) {
	var resource Volume
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("libvirt:index/volume:Volume", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Volume resources.
type volumeState struct {
	BaseVolumeId   *string    `pulumi:"baseVolumeId"`
	BaseVolumeName *string    `pulumi:"baseVolumeName"`
	BaseVolumePool *string    `pulumi:"baseVolumePool"`
	Format         *string    `pulumi:"format"`
	Name           *string    `pulumi:"name"`
	Pool           *string    `pulumi:"pool"`
	Size           *float64   `pulumi:"size"`
	Source         *string    `pulumi:"source"`
	VolumeId       *string    `pulumi:"volumeId"`
	Xml            *VolumeXml `pulumi:"xml"`
}

type VolumeState struct {
	BaseVolumeId   pulumi.StringPtrInput
	BaseVolumeName pulumi.StringPtrInput
	BaseVolumePool pulumi.StringPtrInput
	Format         pulumi.StringPtrInput
	Name           pulumi.StringPtrInput
	Pool           pulumi.StringPtrInput
	Size           pulumi.Float64PtrInput
	Source         pulumi.StringPtrInput
	VolumeId       pulumi.StringPtrInput
	Xml            VolumeXmlPtrInput
}

func (VolumeState) ElementType() reflect.Type {
	return reflect.TypeOf((*volumeState)(nil)).Elem()
}

type volumeArgs struct {
	BaseVolumeId   *string    `pulumi:"baseVolumeId"`
	BaseVolumeName *string    `pulumi:"baseVolumeName"`
	BaseVolumePool *string    `pulumi:"baseVolumePool"`
	Format         *string    `pulumi:"format"`
	Name           *string    `pulumi:"name"`
	Pool           *string    `pulumi:"pool"`
	Size           *float64   `pulumi:"size"`
	Source         *string    `pulumi:"source"`
	VolumeId       *string    `pulumi:"volumeId"`
	Xml            *VolumeXml `pulumi:"xml"`
}

// The set of arguments for constructing a Volume resource.
type VolumeArgs struct {
	BaseVolumeId   pulumi.StringPtrInput
	BaseVolumeName pulumi.StringPtrInput
	BaseVolumePool pulumi.StringPtrInput
	Format         pulumi.StringPtrInput
	Name           pulumi.StringPtrInput
	Pool           pulumi.StringPtrInput
	Size           pulumi.Float64PtrInput
	Source         pulumi.StringPtrInput
	VolumeId       pulumi.StringPtrInput
	Xml            VolumeXmlPtrInput
}

func (VolumeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*volumeArgs)(nil)).Elem()
}

type VolumeInput interface {
	pulumi.Input

	ToVolumeOutput() VolumeOutput
	ToVolumeOutputWithContext(ctx context.Context) VolumeOutput
}

func (*Volume) ElementType() reflect.Type {
	return reflect.TypeOf((**Volume)(nil)).Elem()
}

func (i *Volume) ToVolumeOutput() VolumeOutput {
	return i.ToVolumeOutputWithContext(context.Background())
}

func (i *Volume) ToVolumeOutputWithContext(ctx context.Context) VolumeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VolumeOutput)
}

type VolumeOutput struct{ *pulumi.OutputState }

func (VolumeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Volume)(nil)).Elem()
}

func (o VolumeOutput) ToVolumeOutput() VolumeOutput {
	return o
}

func (o VolumeOutput) ToVolumeOutputWithContext(ctx context.Context) VolumeOutput {
	return o
}

func (o VolumeOutput) BaseVolumeId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringPtrOutput { return v.BaseVolumeId }).(pulumi.StringPtrOutput)
}

func (o VolumeOutput) BaseVolumeName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringPtrOutput { return v.BaseVolumeName }).(pulumi.StringPtrOutput)
}

func (o VolumeOutput) BaseVolumePool() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringPtrOutput { return v.BaseVolumePool }).(pulumi.StringPtrOutput)
}

func (o VolumeOutput) Format() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.Format }).(pulumi.StringOutput)
}

func (o VolumeOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o VolumeOutput) Pool() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringPtrOutput { return v.Pool }).(pulumi.StringPtrOutput)
}

func (o VolumeOutput) Size() pulumi.Float64Output {
	return o.ApplyT(func(v *Volume) pulumi.Float64Output { return v.Size }).(pulumi.Float64Output)
}

func (o VolumeOutput) Source() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringPtrOutput { return v.Source }).(pulumi.StringPtrOutput)
}

func (o VolumeOutput) VolumeId() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.VolumeId }).(pulumi.StringOutput)
}

func (o VolumeOutput) Xml() VolumeXmlPtrOutput {
	return o.ApplyT(func(v *Volume) VolumeXmlPtrOutput { return v.Xml }).(VolumeXmlPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VolumeInput)(nil)).Elem(), &Volume{})
	pulumi.RegisterOutputType(VolumeOutput{})
}
